(function(){function g(a){throw a;}var i=void 0,j=true,k=null,q=false;function aa(a){return function(){return this[a]}}var t,v=this;function ba(a){for(var a=a.split("."),b=v,c;c=a.shift();)if(b[c]!=k)b=b[c];else return k;return b}function ca(){}
function da(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function w(a){return da(a)=="array"}function y(a){var b=da(a);return b=="array"||b=="object"&&typeof a.length=="number"}function z(a){return typeof a=="string"}function ea(a){return typeof a=="number"}function fa(a){return da(a)=="function"}function ga(a){var b=typeof a;return b=="object"&&a!=k||b=="function"}function ha(a){return a[ia]||(a[ia]=++ja)}
var ia="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ja=0;function ka(a,b,c){return a.call.apply(a.bind,arguments)}function oa(a,b,c){a||g(Error());if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function pa(a,b,c){pa=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ka:oa;return pa.apply(k,arguments)}var C=Date.now||function(){return+new Date};function E(a,b){var c=a.split("."),d=v;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==i?d[f]=b:d=d[f]?d[f]:d[f]={}}function F(a,b){function c(){}c.prototype=b.prototype;a.W=b.prototype;a.prototype=new c;a.prototype.constructor=a};function qa(a,b){for(var c=1;c<arguments.length;c++)var d=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}function ra(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function sa(a,b){var c=String(a).toLowerCase(),d=String(b).toLowerCase();return c<d?-1:c==d?0:1}var ta=/^[a-zA-Z0-9\-_.!~*'()]*$/;function ua(a){a=String(a);return!ta.test(a)?encodeURIComponent(a):a}
function va(a){if(!wa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(xa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ya,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(za,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(Aa,"&quot;"));return a}var xa=/&/g,ya=/</g,za=/>/g,Aa=/\"/g,wa=/[&<>\"]/;function G(a){var a=String(a),b=a.indexOf(".");if(b==-1)b=a.length;b=Math.max(0,2-b);return Array(b+1).join("0")+a}function Ba(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Ca,Fa,Ga,Ha;function Ia(){return v.navigator?v.navigator.userAgent:k}Ha=Ga=Fa=Ca=q;var Ja;if(Ja=Ia()){var Ka=v.navigator;Ca=Ja.indexOf("Opera")==0;Fa=!Ca&&Ja.indexOf("MSIE")!=-1;Ga=!Ca&&Ja.indexOf("WebKit")!=-1;Ha=!Ca&&!Ga&&Ka.product=="Gecko"}var La=Ca,H=Fa,I=Ha,J=Ga,Ma=v.navigator,Na=(Ma&&Ma.platform||"").indexOf("Mac")!=-1,Oa;
a:{var Pa="",Qa;if(La&&v.opera)var Sa=v.opera.version,Pa=typeof Sa=="function"?Sa():Sa;else if(I?Qa=/rv\:([^\);]+)(\)|;)/:H?Qa=/MSIE\s+([^\);]+)(\)|;)/:J&&(Qa=/WebKit\/(\S+)/),Qa)var Ta=Qa.exec(Ia()),Pa=Ta?Ta[1]:"";if(H){var Ua,Va=v.document;Ua=Va?Va.documentMode:i;if(Ua>parseFloat(Pa)){Oa=String(Ua);break a}}Oa=Pa}var Wa={};
function K(a){var b;if(!(b=Wa[a])){b=0;for(var c=ra(String(Oa)).split("."),d=ra(String(a)).split("."),f=Math.max(c.length,d.length),e=0;b==0&&e<f;e++){var h=c[e]||"",m=d[e]||"",o=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var r=o.exec(h)||["","",""],n=l.exec(m)||["","",""];if(r[0].length==0&&n[0].length==0)break;b=Ba(r[1].length==0?0:parseInt(r[1],10),n[1].length==0?0:parseInt(n[1],10))||Ba(r[2].length==0,n[2].length==0)||Ba(r[2],n[2])}while(b==0)}b=Wa[a]=b>=0}return b}var Xa={};
function Ya(){return Xa[9]||(Xa[9]=H&&!!document.documentMode&&document.documentMode>=9)};function L(a){Error.captureStackTrace?Error.captureStackTrace(this,L):this.stack=Error().stack||"";if(a)this.message=String(a)}F(L,Error);L.prototype.name="CustomError";function Za(a,b){b.unshift(a);L.call(this,qa.apply(k,b));b.shift();this.Ic=a}F(Za,L);Za.prototype.name="AssertionError";function $a(a,b){g(new Za("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var ab=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function M(a,b){for(var c in a)b.call(i,a[c],c,a)}function bb(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function cb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function db(a,b){for(var c=y(b),d=c?b:arguments,c=c?0:1;c<d.length;c++)if(a=a[d[c]],a===i)break;return a}function eb(a,b,c){a[b]=c}var fb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");
function gb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<fb.length;e++)c=fb[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var N=Array.prototype,hb=N.indexOf?function(a,b,c){return N.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:c<0?Math.max(0,a.length+c):c;if(z(a))return!z(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},O=N.forEach?function(a,b,c){N.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},ib=N.some?function(a,b,c){return N.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(""):a,
e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return j;return q};function jb(a){return N.concat.apply(N,arguments)}function kb(a,b){N.sort.call(a,b||lb)}function mb(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||lb;kb(a,function(a,b){return d(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value}function lb(a,b){return a>b?1:a<b?-1:0};var nb="StopIteration"in v?v.StopIteration:Error("StopIteration");function ob(){}ob.prototype.next=function(){g(nb)};ob.prototype.pa=function(){return this};function pb(a){if(a instanceof ob)return a;if(typeof a.pa=="function")return a.pa(q);if(y(a)){var b=0,c=new ob;c.next=function(){for(;;)if(b>=a.length&&g(nb),b in a)return a[b++];else b++};return c}g(Error("Not implemented"))}
function qb(a,b){if(y(a))try{O(a,b,i)}catch(c){c!==nb&&g(c)}else{a=pb(a);try{for(;;)b.call(i,a.next(),i,a)}catch(d){d!==nb&&g(d)}}};function rb(a){if(typeof a.w=="function")return a.w();if(z(a))return a.split("");if(y(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return bb(a)}function sb(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(y(a)||z(a))O(a,b,c);else{var d;if(typeof a.r=="function")d=a.r();else if(typeof a.w!="function")if(y(a)||z(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else d=cb(a);else d=i;for(var f=rb(a),e=f.length,h=0;h<e;h++)b.call(c,f[h],d&&d[h],a)}};function P(a,b){this.i={};this.e=[];var c=arguments.length;if(c>1){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof P?(c=a.r(),d=a.w()):(c=cb(a),d=bb(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}t=P.prototype;t.b=0;t.ba=0;t.bb=aa("b");t.w=function(){tb(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.i[this.e[b]]);return a};t.r=function(){tb(this);return this.e.concat()};t.q=function(a){return wb(this.i,a)};
t.clear=function(){this.i={};this.ba=this.b=this.e.length=0};t.remove=function(a){return wb(this.i,a)?(delete this.i[a],this.b--,this.ba++,this.e.length>2*this.b&&tb(this),j):q};function tb(a){if(a.b!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];wb(a.i,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.b!=a.e.length){for(var f={},c=b=0;b<a.e.length;)d=a.e[b],wb(f,d)||(a.e[c++]=d,f[d]=1),b++;a.e.length=c}}t.get=function(a,b){return wb(this.i,a)?this.i[a]:b};
t.set=function(a,b){wb(this.i,a)||(this.b++,this.e.push(a),this.ba++);this.i[a]=b};t.p=function(){return new P(this)};t.pa=function(a){tb(this);var b=0,c=this.e,d=this.i,f=this.ba,e=this,h=new ob;h.next=function(){for(;;){f!=e.ba&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(nb);var h=c[b++];return a?h:d[h]}};return h};function wb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function xb(a,b){var c;a instanceof xb?(this.L(b==k?a.k:b),yb(this,a.s),zb(this,a.aa),Ab(this,a.u),Bb(this,a.H),Cb(this,a.A),Db(this,a.l.p()),Eb(this,a.P)):a&&(c=String(a).match(ab))?(this.L(!!b),yb(this,c[1]||"",j),zb(this,c[2]||"",j),Ab(this,c[3]||"",j),Bb(this,c[4]),Cb(this,c[5]||"",j),Db(this,c[6]||"",j),Eb(this,c[7]||"",j)):(this.L(!!b),this.l=new Fb(k,this,this.k))}t=xb.prototype;t.s="";t.aa="";t.u="";t.H=k;t.A="";t.P="";t.Ub=q;t.k=q;
t.toString=function(){if(this.h)return this.h;var a=[];this.s&&a.push(Gb(this.s,Hb),":");this.u&&(a.push("//"),this.aa&&a.push(Gb(this.aa,Hb),"@"),a.push(z(this.u)?encodeURIComponent(this.u):k),this.H!=k&&a.push(":",String(this.H)));this.A&&(this.u&&this.A.charAt(0)!="/"&&a.push("/"),a.push(Gb(this.A,this.A.charAt(0)=="/"?Ib:Jb)));var b=String(this.l);b&&a.push("?",b);this.P&&a.push("#",Gb(this.P,Kb));return this.h=a.join("")};
t.p=function(){var a=this.s,b=this.aa,c=this.u,d=this.H,f=this.A,e=this.l.p(),h=this.P,m=new xb(k,this.k);a&&yb(m,a);b&&zb(m,b);c&&Ab(m,c);d&&Bb(m,d);f&&Cb(m,f);e&&Db(m,e);h&&Eb(m,h);return m};function yb(a,b,c){Q(a);delete a.h;a.s=c?b?decodeURIComponent(b):"":b;if(a.s)a.s=a.s.replace(/:$/,"")}function zb(a,b,c){Q(a);delete a.h;a.aa=c?b?decodeURIComponent(b):"":b}function Ab(a,b,c){Q(a);delete a.h;a.u=c?b?decodeURIComponent(b):"":b}
function Bb(a,b){Q(a);delete a.h;b?(b=Number(b),(isNaN(b)||b<0)&&g(Error("Bad port number "+b)),a.H=b):a.H=k}function Cb(a,b,c){Q(a);delete a.h;a.A=c?b?decodeURIComponent(b):"":b}function Db(a,b,c){Q(a);delete a.h;b instanceof Fb?(a.l=b,a.l.$=a,a.l.L(a.k)):(c||(b=Gb(b,Lb)),a.l=new Fb(b,a,a.k))}function Mb(a,b,c){Q(a);delete a.h;w(c)||(c=[String(c)]);a=a.l;R(a);Nb(a);b=S(a,b);if(a.q(b)){var d=a.d.get(b);w(d)?a.b-=d.length:a.b--}c.length>0&&(a.d.set(b,c),a.b+=c.length)}
function Eb(a,b,c){Q(a);delete a.h;a.P=c?b?decodeURIComponent(b):"":b}function Q(a){a.Ub&&g(Error("Tried to modify a read-only Uri"))}t.L=function(a){this.k=a;this.l&&this.l.L(a);return this};var Ob=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;function Gb(a,b){var c=k;z(a)&&(c=a,Ob.test(c)||(c=encodeURI(a)),c.search(b)>=0&&(c=c.replace(b,Pb)));return c}function Pb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Hb=/[#\/\?@]/g,Jb=/[\#\?:]/g,Ib=/[\#\?]/g,Lb=/[\#\?@]/g,Kb=/#/g;
function Fb(a,b,c){this.o=a||k;this.$=b||k;this.k=!!c}function R(a){if(!a.d&&(a.d=new P,a.b=0,a.o))for(var b=a.o.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=k,e=k;d>=0?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=S(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}t=Fb.prototype;t.d=k;t.b=k;t.bb=function(){R(this);return this.b};
t.add=function(a,b){R(this);Nb(this);a=S(this,a);if(this.q(a)){var c=this.d.get(a);w(c)?c.push(b):this.d.set(a,[c,b])}else this.d.set(a,b);this.b++;return this};t.remove=function(a){R(this);a=S(this,a);if(this.d.q(a)){Nb(this);var b=this.d.get(a);w(b)?this.b-=b.length:this.b--;return this.d.remove(a)}return q};t.clear=function(){Nb(this);this.d&&this.d.clear();this.b=0};t.q=function(a){R(this);a=S(this,a);return this.d.q(a)};
t.r=function(){R(this);for(var a=this.d.w(),b=this.d.r(),c=[],d=0;d<b.length;d++){var f=a[d];if(w(f))for(var e=0;e<f.length;e++)c.push(b[d]);else c.push(b[d])}return c};t.w=function(a){R(this);var b=[];if(a)a=S(this,a),this.q(a)&&(b=jb(b,this.d.get(a)));else for(var a=this.d.w(),c=0;c<a.length;c++)b=jb(b,a[c]);return b};t.set=function(a,b){R(this);Nb(this);a=S(this,a);if(this.q(a)){var c=this.d.get(a);w(c)?this.b-=c.length:this.b--}this.d.set(a,b);this.b++;return this};
t.get=function(a,b){R(this);a=S(this,a);if(this.q(a)){var c=this.d.get(a);return w(c)?c[0]:c}else return b};t.toString=function(){if(this.o)return this.o;if(!this.d)return"";for(var a=[],b=0,c=this.d.r(),d=0;d<c.length;d++){var f=c[d],e=ua(f),f=this.d.get(f);if(w(f))for(var h=0;h<f.length;h++)b>0&&a.push("&"),a.push(e),f[h]!==""&&a.push("=",ua(f[h])),b++;else b>0&&a.push("&"),a.push(e),f!==""&&a.push("=",ua(f)),b++}return this.o=a.join("")};
function Nb(a){delete a.xa;delete a.o;a.$&&delete a.$.h}t.p=function(){var a=new Fb;if(this.xa)a.xa=this.xa;if(this.o)a.o=this.o;if(this.d)a.d=this.d.p();return a};function S(a,b){var c=String(b);a.k&&(c=c.toLowerCase());return c}t.L=function(a){a&&!this.k&&(R(this),Nb(this),sb(this.d,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.add(d,a))},this));this.k=a};function Qb(a){this.dataset=a}function Rb(a,b){var c={sum:0,timeslot:{},columns:b},d=C();console.log("makina.Dataset.prototype.Sum");var f=0,e={c:0};O(a.dataset,function(c){M(c,function(c,d,h){O(b,function(b){b.lastIndexOf("timeslot",0)==0?e[b]=a.Oa([e[b],h[b]]):isNaN(h[b])||(f+=h[b])})})});O(b,function(a){e.c+=e[a].c});c.sum=f;c.timeslot=e;d=C()-d;return{response:c,ms:d}}
function Sb(a,b,c,d){function f(a){var c=j;O(b,function(b,f){d[f]!=k&&a[b]!=d[f]&&(c=q)});return c}function e(a){var b=q,c;for(c in o){var d=o[c];if(d.val==a.val)o[c].item=h(d.item,a.item),b=j}b||o.push(a)}function h(b,d){O(c,function(c){(c in b?b[c]:i)==i?b[c]=d[c]:c.lastIndexOf("timeslot",0)==0?b[c]=a.Oa([b[c],d[c]]):b[c]+=d[c]});return b}var m=b,m=m.concat(c);d!==i||(d=k);var o=[],l=C();O(a.dataset,function(a){var c={groups:{key:"",val:""},item:{}},h=[];O(b,function(b){b=db(a,b);h.push(b)});c.val=
h.join("|");var l={};O(m,function(b){l[b]=a[b]});c.item=l;d!=k?f(l)&&e(c):e(c)});var r=[],n;for(n in o)r.push(o[n].item);mb(r,function(a,c){return sa(a[b[0]],c[b[0]])});l=C()-l;return{response:{columns:m,rows:r},ms:l}}
function Tb(a,b){function c(a,b){var c=q;O(d[a],function(a){a==b&&(c=j)});c||d[a].push(b)}var b=b.sort(),d={},f=C();O(b,function(a){d[a]=[]});console.log("makina.Dataset.prototype.GetColumnValues");O(a.dataset,function(a){O(b,function(b){c(b,a[b])})});O(b,function(a){mb(d[a],function(a,b){return sa(a,b)})});var f=C()-f,e={};e.columns=b;e.rows=d;return{response:e,ms:f}}
Qb.prototype.Oa=function(a){var b={c:0};O(a,function(a){M(a,function(a,c){var e=0;a.c>0&&(e=a.c);c in b?b[c].c+=e:eb(b,c,{c:e});b.c+=e;M(a,function(a,d){d!="c"&&(d in b[c]?b[c][d].c+=a.c:eb(b[c],d,{c:a.c}));M(a,function(a,e){e!="c"&&(e in b[c][d]?b[c][d][e].c+=a.c:eb(b[c][d],e,{c:a.c}));M(a,function(h,n){n!="c"&&(n in b[c][d][e]?b[c][d][e][n].c+=a.c:b[c][d][e][n]={c:a.c})})})})})});return b};function T(a,b){this.options=a;this.Ga=j;this.v=a.fetchOptions;this.t="";if(b!=i)this.t=b;if(this.t!="")this.za=z(this.t)?document.getElementById(this.t):this.t;this.Cb=this.options.url;this.M=this.options.refreshTime*1E3;this.sa=this.options.responseSuccessCallBack;this.ra=this.options.responseErrorCallBack;this.qa=this.options.responseColumnsCallBack;this.ac=[];this.D=[];this.wa=[];this.Pa=Math.round((new Ub(1999,1,1,10,10,10)).getTime()/1E3);this.ga=new Qb(this.D);V(this,"Start Widget","blue");
Vb(this)}t=T.prototype;t.vb=function(a){var b=q;O(this.v,function(c){c.id==a.id&&(b=j)});b||this.v.push(a);return!b};t.zb=function(a){var b=q,c=[];O(this.v,function(d){d.id==a?b=j:c.push(d)});if(b)this.v=c;return b};t.yb=aa("wa");t.Bb=function(){this.Ga=q;return j};t.Ab=function(){return this.Ga=j};function V(a,b,c){var d=new Ub,b=d.Z(j)+"."+d.getMilliseconds()+" : "+b,d="black";c!=i&&(d=c);console.log(b);a.t!=i&&a.za!=i&&a.za.appendChild(Wb("<div style='color:"+d+" ' >"+b+"</div>"))}
function Xb(a){if(!ea(a.M))a.M=0;if(a.M>0)a.m==k||a.m==i?(V(a,"Create Timer and Start Timer "+a.M/1E3+" ms"),a.m=new Yb(a.M),a.m.start(),Zb(a.m,$b,function(){a.Ga&&Vb(a)})):(V(a,"Start Timer..."),a.m.start())}
function ac(a,b){a.ac=b;a.wa=b.columns;bc(a,b.rows);var c={};c.columns=a.wa;c.rows=a.D;a.sa!=k&&a.sa&&a.sa(c);a.qa!=k&&a.qa&&a.qa(c);a.ga.dataset=a.D;C();V(a,"Fetch Event Options Started","red");var d=0,f=0,e=q;if(a.v!=k)f=a.v.length;ea(f)||(f=0);if(f>0)var h=setInterval(function(){if(!e){e=j;var b=a.v[d],c=C();V(a,"Start "+b.name+" ProcessFetchItems","green");if(b.type=="sum"){var l=Rb(a.ga,b.columns);b.fetchCallBack!=k&&b.fetchCallBack(l)}else b.type=="groupby"?(l=Sb(a.ga,b.byColumns,b.columns,
b.byValues),b.fetchCallBack!=k&&b.fetchCallBack(l)):b.type=="keyvalues"&&(console.log("Call get key Values Array"),l=Tb(a.ga,b.byColumns),b.fetchCallBack!=k&&b.fetchCallBack(l));c=C()-c;V(a,"End "+b.name+" ProcessFetchItems ms="+c,"green");++d==f&&(Xb(a),clearInterval(h));e=q}},200);else Xb(a);V(a,"Fetch Event Options Endddddddddd","red")}function cc(a){a.m==k||a.m==i||(a.m.stop(),V(a,"Stop Timer"))}
function Vb(a){var b=new dc(a.Cb+"/"+a.Pa);b.X=45E3;if(a.t!=i)a.za.innerHTML="";V(a,"Request Data With JSONP","blue");cc(a);var c=C();b.send({},function(b){var f=C()-c;V(a,"Response JSONP Request ms="+f);ac(a,b)},function(b){a.m.start();a.ra!=k&&a.ra&&a.ra(b)})}
function bc(a,b){if(b.length!=0){var c=new Ub;a.Pa=Math.round(c.getTime()/1E3)}V(a,"Start decode code ","yellow");c=C();O(b,function(c,f){M(c,function(a,c){if(c.lastIndexOf("timeslot",0)==0){for(var d=b[f],o=ec,l=b[f][c],r="",n,B,A,s,p,D=0,l=l.replace(/[^A-Za-z0-9\+\/\=]/g,"");D<l.length;)n="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(l.charAt(D++)),B="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(l.charAt(D++)),s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(l.charAt(D++)),
p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(l.charAt(D++)),n=n<<2|B>>4,B=(B&15)<<4|s>>2,A=(s&3)<<6|p,r+=String.fromCharCode(n),s!=64&&(r+=String.fromCharCode(B)),p!=64&&(r+=String.fromCharCode(A));l="";for(n=D=p=s=0;s<r.length;)p=r.charCodeAt(s),p<128?(l+=String.fromCharCode(p),s++):p>191&&p<224?(D=r.charCodeAt(s+1),l+=String.fromCharCode((p&31)<<6|D&63),s+=2):(D=r.charCodeAt(s+1),n=r.charCodeAt(s+2),l+=String.fromCharCode((p&15)<<12|(D&63)<<6|n&63),s+=3);d[c]=o(l)}});
fc(a,c)});V(a,"End of decode code ms="+(C()-c),"yellow")}function fc(a,b){var c=q,d={};try{O(a.D,function(e,f){e._rowKey==b._rowKey&&(a.D[f]=b,c=j,g(d))})}catch(f){}c||a.D.push(b)};function gc(a){return hc(a||arguments.callee.caller,[])}
function hc(a,b){var c=[];if(hb(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(ic(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=ic(e))?e:"[fn]";break;default:e=typeof e}e.length>40&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(hc(a.caller,b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function ic(a){if(jc[a])return jc[a];a=String(a);if(!jc[a]){var b=/function ([^\(]+)/.exec(a);jc[a]=b?b[1]:"[Anonymous]"}return jc[a]}var jc={};function kc(){}kc.prototype.Xa=q;kc.prototype.F=function(){if(!this.Xa)this.Xa=j,this.j()};kc.prototype.j=function(){this.Ob&&lc.apply(k,this.Ob)};function lc(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];y(d)?lc.apply(k,d):d&&typeof d.F=="function"&&d.F()}};function mc(a,b){this.ib=b;this.Q=[];a>this.ib&&g(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.Q.push(this.fa())}F(mc,kc);t=mc.prototype;t.Ta=k;t.Wa=k;function nc(a,b){a.Q.length<a.ib?a.Q.push(b):a.ya(b)}t.fa=function(){return this.Ta?this.Ta():{}};t.ya=function(a){if(this.Wa)this.Wa(a);else if(ga(a))if(fa(a.F))a.F();else for(var b in a)delete a[b]};t.j=function(){mc.W.j.call(this);for(var a=this.Q;a.length;)this.ya(a.pop());delete this.Q};function oc(a,b,c,d,f){this.reset(a,b,c,d,f)}oc.prototype.cc=0;oc.prototype.ab=k;oc.prototype.$a=k;var pc=0;oc.prototype.reset=function(a,b,c,d,f){this.cc=typeof f=="number"?f:pc++;this.Lc=d||C();this.S=a;this.Xb=b;this.Hc=c;delete this.ab;delete this.$a};oc.prototype.nb=function(a){this.S=a};function W(a){this.Yb=a}W.prototype.z=k;W.prototype.S=k;W.prototype.va=k;W.prototype.eb=k;function qc(a,b){this.name=a;this.value=b}qc.prototype.toString=aa("name");var rc=new qc("INFO",800),Bc=new qc("CONFIG",700);t=W.prototype;t.getParent=aa("z");t.nb=function(a){this.S=a};function Cc(a){if(a.S)return a.S;if(a.z)return Cc(a.z);$a("Root logger has no level set.");return k}
t.log=function(a,b,c){if(a.value>=Cc(this).value){a=this.Rb(a,b,c);b="log:"+a.Xb;v.console&&(v.console.timeStamp?v.console.timeStamp(b):v.console.markTimeline&&v.console.markTimeline(b));v.msWriteProfilerMark&&v.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.eb)for(var f=0,e=i;e=c.eb[f];f++)e(d);b=b.getParent()}}};
t.Rb=function(a,b,c){var d=new oc(a,String(b),this.Yb);if(c){d.ab=c;var f;var e=arguments.callee.caller;try{var h;var m=ba("window.location.href");if(z(c))h={message:c,name:"Unknown error",lineNumber:"Not available",fileName:m,stack:"Not available"};else{var o,l,r=q;try{o=c.lineNumber||c.Gc||"Not available"}catch(n){o="Not available",r=j}try{l=c.fileName||c.filename||c.sourceURL||m}catch(B){l="Not available",r=j}h=r||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:o,
fileName:l,stack:c.stack||"Not available"}:c}f="Message: "+va(h.message)+'\nUrl: <a href="view-source:'+h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+va(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+va(gc(e)+"-> ")}catch(A){f="Exception trying to expose exception! You win, we lose. "+A}d.$a=f}return d};t.info=function(a,b){this.log(rc,a,b)};var Dc={},Ec=k;
function Fc(a){Ec||(Ec=new W(""),Dc[""]=Ec,Ec.nb(Bc));var b;if(!(b=Dc[a])){b=new W(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Fc(a.substr(0,c));if(!c.va)c.va={};c.va[d]=b;b.z=c;Dc[a]=b}return b};function Gc(){this.N=[];this.Ja=new P;this.sb=this.tb=this.ub=this.pb=0;this.V=new P;this.Ra=this.rb=0;this.kb=1;this.Aa=new mc(0,4E3);this.Aa.fa=function(){return new Hc};this.qb=new mc(0,50);this.qb.fa=function(){return new Ic};var a=this;this.Fa=new mc(0,2E3);this.Fa.fa=function(){return String(a.kb++)};this.Fa.ya=function(){};this.Nb=3}function Ic(){this.Na=this.time=this.ea=0}
Ic.prototype.toString=function(){var a=[];a.push(this.type," ",this.ea," (",Math.round(this.time*10)/10," ms)");this.Na&&a.push(" [VarAlloc = ",this.Na,"]");return a.join("")};function Hc(){}function Jc(a,b,c,d){var f=[];c==-1?f.push("    "):f.push(Kc(a.Za-c));f.push(" ",Lc(a.Za-b));a.Ba==0?f.push(" Start        "):a.Ba==1?(f.push(" Done "),f.push(Kc(a.Kc-a.startTime)," ms ")):f.push(" Comment      ");f.push(d,a);a.ec>0&&f.push("[VarAlloc ",a.ec,"] ");return f.join("")}
Hc.prototype.toString=function(){return this.type==k?this.Ib:"["+this.type+"] "+this.Ib};Gc.prototype.reset=function(a){this.Nb=a;for(a=0;a<this.N.length;a++){var b=this.Aa.id;b&&nc(this.Fa,b);nc(this.Aa,this.N[a])}this.N.length=0;this.Ja.clear();this.pb=C();this.Ra=this.rb=this.sb=this.tb=this.ub=0;b=this.V.r();for(a=0;a<b.length;a++){var c=this.V.get(b[a]);c.ea=0;c.time=0;c.Na=0;nc(this.qb,c)}this.V.clear()};
Gc.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.N.length;d++){var f=this.N[d];f.Ba==1&&c.pop();a.push(" ",Jc(f,this.pb,b,c.join("")));b=f.Za;a.push("\n");f.Ba==0&&c.push("|  ")}if(this.Ja.bb()!=0){var e=C();a.push(" Unstopped timers:\n");qb(this.Ja,function(b){a.push("  ",b," (",e-b.startTime," ms, started at ",Lc(b.startTime),")\n")})}b=this.V.r();for(d=0;d<b.length;d++)c=this.V.get(b[d]),c.ea>1&&a.push(" TOTAL ",c,"\n");a.push("Total tracers created ",this.rb,"\n","Total comments created ",
this.Ra,"\n","Overhead start: ",this.ub," ms\n","Overhead end: ",this.tb," ms\n","Overhead comment: ",this.sb," ms\n");return a.join("")};function Kc(a){var a=Math.round(a),b="";a<1E3&&(b=" ");a<100&&(b="  ");a<10&&(b="   ");return b+a}function Lc(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new Gc;var Mc;!H||Ya();!I&&!H||H&&Ya()||I&&K("1.9.1");H&&K("9");function Nc(a){return a?new Oc(a.nodeType==9?a:a.ownerDocument||a.document):Mc||(Mc=new Oc)}function Pc(a,b){M(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in Qc?a.setAttribute(Qc[d],b):d.lastIndexOf("aria-",0)==0?a.setAttribute(d,b):a[d]=b})}var Qc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Oc(a){this.Ya=a||v.document||document}Oc.prototype.cb=function(a){return z(a)?this.Ya.getElementById(a):a};Oc.prototype.createElement=function(a){return this.Ya.createElement(a)};Oc.prototype.appendChild=function(a,b){a.appendChild(b)};function Rc(){}var Sc=0;t=Rc.prototype;t.key=0;t.K=q;t.Qa=q;t.ja=function(a,b,c,d,f,e){fa(a)?this.gb=j:a&&a.handleEvent&&fa(a.handleEvent)?this.gb=q:g(Error("Invalid listener argument"));this.T=a;this.lb=b;this.src=c;this.type=d;this.capture=!!f;this.Ea=e;this.Qa=q;this.key=++Sc;this.K=q};t.handleEvent=function(a){return this.gb?this.T.call(this.Ea||this.src,a):this.T.handleEvent.call(this.T,a)};!H||Ya();var Tc=!H||Ya(),Uc=H&&!K("8");!J||K("528");I&&K("1.9b")||H&&K("8")||La&&K("9.5")||J&&K("528");I&&!K("8")||H&&K("9");function X(a,b){this.type=a;this.currentTarget=this.target=b}F(X,kc);t=X.prototype;t.j=function(){delete this.type;delete this.target;delete this.currentTarget};t.I=q;t.Va=q;t.oa=j;t.preventDefault=function(){this.Va=j;this.oa=q};function Vc(a){Vc[" "](a);return a}Vc[" "]=ca;function Wc(a,b){a&&this.ja(a,b)}F(Wc,X);t=Wc.prototype;t.target=k;t.relatedTarget=k;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=q;t.altKey=q;t.shiftKey=q;t.metaKey=q;t.$b=q;t.Ca=k;
t.ja=function(a,b){var c=this.type=a.type;X.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(I){var f;a:{try{Vc(d.nodeName);f=j;break a}catch(e){}f=q}f||(d=k)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=J||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=J||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.$b=Na?a.metaKey:a.ctrlKey;this.state=a.state;this.Ca=a;a.Va&&this.preventDefault();delete this.I};
t.preventDefault=function(){Wc.W.preventDefault.call(this);var a=this.Ca;if(a.preventDefault)a.preventDefault();else if(a.returnValue=q,Uc)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};t.j=function(){Wc.W.j.call(this);this.relatedTarget=this.currentTarget=this.target=this.Ca=k};var Xc={},Y={},Z={},Yc={};
function Zb(a,b,c,d,f){if(b)if(w(b))for(var e=0;e<b.length;e++)Zb(a,b[e],c,d,f);else{var d=!!d,h=Y;b in h||(h[b]={b:0,g:0});h=h[b];d in h||(h[d]={b:0,g:0},h.b++);var h=h[d],m=ha(a),o;h.g++;if(h[m]){o=h[m];for(e=0;e<o.length;e++)if(h=o[e],h.T==c&&h.Ea==f){if(h.K)break;return}}else o=h[m]=[],h.b++;e=Zc();e.src=a;h=new Rc;h.ja(c,e,a,b,d,f);c=h.key;e.key=c;o.push(h);Xc[c]=h;Z[m]||(Z[m]=[]);Z[m].push(h);a.addEventListener?(a==v||!a.Ua)&&a.addEventListener(b,e,d):a.attachEvent(b in Yc?Yc[b]:Yc[b]="on"+
b,e)}else g(Error("Invalid event type"))}function Zc(){var a=$c,b=Tc?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function ad(a,b,c,d,f){if(w(b))for(var e=0;e<b.length;e++)ad(a,b[e],c,d,f);else{d=!!d;a:{e=Y;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ha(a),e[a]))){a=e[a];break a}a=k}if(a)for(e=0;e<a.length;e++)if(a[e].T==c&&a[e].capture==d&&a[e].Ea==f){bd(a[e].key);break}}}
function bd(a){if(Xc[a]){var b=Xc[a];if(!b.K){var c=b.src,d=b.type,f=b.lb,e=b.capture;c.removeEventListener?(c==v||!c.Ua)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in Yc?Yc[d]:Yc[d]="on"+d,f);c=ha(c);f=Y[d][e][c];if(Z[c]){var h=Z[c],m=hb(h,b);m>=0&&N.splice.call(h,m,1);h.length==0&&delete Z[c]}b.K=j;f.jb=j;cd(d,e,c,f);delete Xc[a]}}}
function cd(a,b,c,d){if(!d.la&&d.jb){for(var f=0,e=0;f<d.length;f++)d[f].K?d[f].lb.src=k:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.jb=q;e==0&&(delete Y[a][b][c],Y[a][b].b--,Y[a][b].b==0&&(delete Y[a][b],Y[a].b--),Y[a].b==0&&delete Y[a])}}function dd(a){var b,c=0,d=b==k;b=!!b;if(a==k)M(Z,function(a){for(var e=a.length-1;e>=0;e--){var f=a[e];if(d||b==f.capture)bd(f.key),c++}});else if(a=ha(a),Z[a])for(var a=Z[a],f=a.length-1;f>=0;f--){var e=a[f];if(d||b==e.capture)bd(e.key),c++}}
function ed(a,b,c,d,f){var e=1,b=ha(b);if(a[b]){a.g--;a=a[b];a.la?a.la++:a.la=1;try{for(var h=a.length,m=0;m<h;m++){var o=a[m];o&&!o.K&&(e&=fd(o,f)!==q)}}finally{a.la--,cd(c,d,b,a)}}return Boolean(e)}function fd(a,b){var c=a.handleEvent(b);a.Qa&&bd(a.key);return c}
function $c(a,b){if(!Xc[a])return j;var c=Xc[a],d=c.type,f=Y;if(!(d in f))return j;var f=f[d],e,h;if(!Tc){e=b||ba("window.event");var m=j in f,o=q in f;if(m){if(e.keyCode<0||e.returnValue!=i)return j;a:{var l=q;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(r){l=j}if(l||e.returnValue==i)e.returnValue=j}}l=new Wc;l.ja(e,this);e=j;try{if(m){for(var n=[],B=l.currentTarget;B;B=B.parentNode)n.push(B);h=f[j];h.g=h.b;for(var A=n.length-1;!l.I&&A>=0&&h.g;A--)l.currentTarget=n[A],e&=ed(h,n[A],d,j,l);if(o){h=
f[q];h.g=h.b;for(A=0;!l.I&&A<n.length&&h.g;A++)l.currentTarget=n[A],e&=ed(h,n[A],d,q,l)}}else e=fd(c,l)}finally{if(n)n.length=0;l.F()}return e}d=new Wc(b,this);try{e=fd(c,d)}finally{d.F()}return e};function gd(){}(function(a){a.Qb=function(){if(!a.Tb)a.Tb=new a}})(gd);gd.prototype.kb=0;gd.Qb();function hd(){}F(hd,kc);t=hd.prototype;t.Ua=j;t.Ka=k;t.addEventListener=function(a,b,c,d){Zb(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){ad(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=a.type||a,c=Y;if(b in c){if(z(a))a=new X(a,this);else if(a instanceof X)a.target=a.target||this;else{var d=a,a=new X(b,this);gb(a,d)}var d=1,f,c=c[b],b=j in c,e;if(b){f=[];for(e=this;e;e=e.Ka)f.push(e);e=c[j];e.g=e.b;for(var h=f.length-1;!a.I&&h>=0&&e.g;h--)a.currentTarget=f[h],d&=ed(e,f[h],a.type,j,a)&&a.oa!=q}if(q in c)if(e=c[q],e.g=e.b,b)for(h=0;!a.I&&h<f.length&&e.g;h++)a.currentTarget=f[h],d&=ed(e,f[h],a.type,q,a)&&a.oa!=q;else for(f=this;!a.I&&f&&e.g;f=f.Ka)a.currentTarget=
f,d&=ed(e,f,a.type,q,a)&&a.oa!=q;a=Boolean(d)}else a=j;return a};t.j=function(){hd.W.j.call(this);dd(this);this.Ka=k};function id(){return j};function ec(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var jd=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!z(a))return[a];if(z(c)&&(c=z(c)?document.getElementById(c):c,!c))return[];var c=c||document,e=c.ownerDocument||c.documentElement;la=c.contentType&&c.contentType=="application/xml"||La&&(c.doctype||e.toString()=="[object XMLDocument]")||!!e&&(H?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.ma?e:b(e)}function b(a){if(a&&a.ma)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(a.length<2)return b;
U++;if(H&&la){var c=U+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(H&&a.Jb)try{for(d=1;e=a[d];d++)D(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=U);for(d=1;e=a[d];d++)a[d]._zipIdx!=U&&b.push(e),e._zipIdx=U}return b}function c(a,b){if(!b)return 1;var c=Hd(a);return!b[c]?b[c]=1:0}function d(a,b){if(tc){var c=uc[a];if(c&&!b)return c}if(c=vc[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");a.indexOf("#")>=
0&&e&&(b=j);if(tc&&!b&&">~+".indexOf(c)==-1&&(!H||a.indexOf(":")==-1)&&!(wc&&a.indexOf(".")>=0)&&a.indexOf(":contains")==-1&&a.indexOf("|=")==-1){var h=">~+".indexOf(a.charAt(a.length-1))>=0?a+" *":a;return uc[a]=function(b){try{9==b.nodeType||e||g("");var c=b.querySelectorAll(h);H?c.Jb=j:c.ma=j;return c}catch(f){return d(a,j)(b)}}}else{var l=a.split(/\s*,\s*/);return vc[a]=l.length<2?f(a):function(a){for(var b=0,c=[],d;d=l[b++];)c=c.concat(f(d)(a));return c}}}function f(a){var b=xc(ra(a));if(b.length==
1){var c=e(b[0]);return function(a){if(a=c(a,[]))a.ma=j;return a}}return function(a){for(var a=ma(a),c,d,f=b.length,sc,h,ub=0;ub<f;ub++){h=[];c=b[ub];d=a.length-1;if(d>0)sc={},h.ma=j;d=e(c);for(var l=0;c=a[l];l++)d(c,h,sc);if(!h.length)break;a=h}return h}}function e(a){var b=yc[a.J];if(b)return b;var c=a.fb,c=c?c.na:"",d=l(a,{G:1}),e="*"==a.f,f=document.getElementsByClassName;if(c){f={G:1};if(e)f.f=1;d=l(a,f);"+"==c?b=o(d):"~"==c?b=m(d):">"==c&&(b=h(d))}else if(a.id)d=!a.hb&&e?id:l(a,{G:1,id:1}),
b=function(b,c){var e=Nc(b).cb(a.id);if(e&&d(e))if(9==b.nodeType)return ma(e,c);else{for(var f=e.parentNode;f;){if(f==b)break;f=f.parentNode}if(f)return ma(e,c)}};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.n.length&&!wc)var d=l(a,{G:1,n:1,id:1}),n=a.n.join(" "),b=function(a,b){for(var c=ma(0,b),e,f=0,h=a.getElementsByClassName(n);e=h[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.hb?b=function(b,c){for(var d=ma(0,c),e,f=0,h=b.getElementsByTagName(a.Da());e=h[f++];)d.push(e);return d}:
(d=l(a,{G:1,f:1,id:1}),b=function(b,c){for(var e=ma(0,c),f,h=0,Gd=b.getElementsByTagName(a.Da());f=Gd[h++];)d(f,b)&&e.push(f);return e});return yc[a.J]=b}function h(a){a=a||id;return function(b,d,e){for(var f=0,h=b[zc];b=h[f++];)Da(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function m(a){return function(b,d,e){for(b=b[Ea];b;){if(Da(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[Ea]}return d}}function o(a){return function(b,d,e){for(;b=b[Ea];)if(!Ra||D(b)){(!e||c(b,e))&&a(b)&&d.push(b);break}return d}}
function l(a,b){if(!a)return id;var b=b||{},c=k;b.G||(c=na(c,D));b.f||a.f!="*"&&(c=na(c,function(b){return b&&b.tagName==a.Da()}));b.n||O(a.n,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=na(c,function(a){return d.test(a.className)});c.ea=b});b.B||O(a.B,function(a){var b=a.name;vb[b]&&(c=na(c,vb[b](b,a.value)))});b.ca||O(a.ca,function(a){var b,d=a.ta;a.type&&Ac[a.type]?b=Ac[a.type](d,a.Ia):d.length&&(b=Id(d));b&&(c=na(c,b))});b.id||a.id&&(c=na(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=id);return c}function r(a){return B(a)%2}function n(a){return!(B(a)%2)}function B(a){var b=a.parentNode,c=0,d=b[zc],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&e>=0&&f>=0)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Ea])if(Da(b))b._i=++c,a===b&&(e=c);return e}function A(a){for(;a=a[Ea];)if(Da(a))return q;return j}function s(a){for(;a=a[Jd];)if(Da(a))return q;return j}function p(a,b){return!a?"":b=="class"?a.className||"":b=="for"?a.htmlFor||"":b=="style"?a.style.cssText||
"":(la?a.getAttribute(b):a.getAttribute(b,2))||""}function D(a){return 1==a.nodeType}function na(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function xc(a){function b(){if(n>=0)u.id=c(n,x).replace(/\\/g,""),n=-1;if(o>=0){var a=o==x?k:c(o,x);">~+".indexOf(a)<0?u.f=a:u.na=a;o=-1}m>=0&&(u.n.push(c(m+1,x).replace(/\\/g,"")),m=-1)}function c(b,d){return ra(a.slice(b,d))}a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var d=[],e=-1,f=-1,h=-1,l=-1,m=-1,n=-1,
o=-1,r="",p="",A,x=0,B=a.length,u=k,s=k;r=p,p=a.charAt(x),x<B;x++)if(r!="\\")if(u||(A=x,u={J:k,B:[],ca:[],n:[],f:k,na:k,id:k,Da:function(){return la?this.Zb:this.f}},o=x),e>=0)if(p=="]"){s.ta?s.Ia=c(h||e+1,x):s.ta=c(e+1,x);if((e=s.Ia)&&(e.charAt(0)=='"'||e.charAt(0)=="'"))s.Ia=e.slice(1,-1);u.ca.push(s);s=k;e=h=-1}else{if(p=="=")h="|~^$*".indexOf(r)>=0?r:"",s.type=h+p,s.ta=c(e+1,x-h.length),h=x+1}else if(f>=0){if(p==")"){if(l>=0)s.value=c(f+1,x);l=f=-1}}else if(p=="#")b(),n=x+1;else if(p==".")b(),
m=x;else if(p==":")b(),l=x;else if(p=="[")b(),e=x,s={};else if(p=="(")l>=0&&(s={name:c(l+1,x),value:k},u.B.push(s)),f=x;else if(p==" "&&r!=p){b();l>=0&&u.B.push({name:c(l+1,x)});u.hb=u.B.length||u.ca.length||u.n.length;u.Jc=u.J=c(A,x);u.Zb=u.f=u.na?k:u.f||"*";if(u.f)u.f=u.f.toUpperCase();if(d.length&&d[d.length-1].na)u.fb=d.pop(),u.J=u.fb.J+" "+u.J;d.push(u);u=k}return d}function ma(a,b){var c=b||[];a&&c.push(a);return c}var wc=J&&document.compatMode=="BackCompat",zc=document.firstChild.children?
"children":"childNodes",la=q,Ac={"*=":function(a,b){return function(c){return p(c,a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return p(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+p(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+p(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){b=" "+b;return function(c){c=" "+p(c,a);return c==b||c.indexOf(b+"-")==0}},"=":function(a,b){return function(c){return p(c,a)==
b}}},Ra=typeof document.firstChild.nextElementSibling=="undefined",Ea=!Ra?"nextElementSibling":"nextSibling",Jd=!Ra?"previousElementSibling":"previousSibling",Da=Ra?D:id,vb={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return s},"last-child":function(){return A},"only-child":function(){return function(a){return!s(a)?q:!A(a)?q:j}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;
if(c===1||c==3)return q}return j}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=xc(b)[0],d={G:1};if(c.f!="*")d.f=1;if(!c.n.length)d.n=1;var e=l(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if(b=="odd")return r;else if(b=="even")return n;if(b.indexOf("n")!=-1){var c=b.split("n",2),d=c[0]?c[0]=="-"?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,h=-1;d>0?e<0?e=e%d&&d+
e%d:e>0&&(e>=d&&(f=e-e%d),e%=d):d<0&&(d*=-1,e>0&&(h=e,e%=d));if(d>0)return function(a){a=B(a);return a>=f&&(h<0||a<=h)&&a%d==e};else b=e}var l=parseInt(b,10);return function(a){return B(a)==l}}},Id=H?function(a){var b=a.toLowerCase();b=="class"&&(a="className");return function(c){return la?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},yc={},vc={},uc={},tc=!!document.querySelectorAll&&(!J||K("526")),U=0,Hd=H?function(a){return la?a.getAttribute("_uid")||
a.setAttribute("_uid",++U)||U:a.uniqueID}:function(a){return a._uid||(a._uid=++U)};a.B=vb;return a}();E("goog.dom.query",jd);E("goog.dom.query.pseudos",jd.B);function kd(){P.call(this)}F(kd,P);var ld=document.createElement("div");function Wb(a){ld.innerHTML=a;return ld.removeChild(ld.firstChild)};var md={jc:["BC","AD"],ic:["Before Christ","Anno Domini"],lc:"J,F,M,A,M,J,J,A,S,O,N,D".split(","),sc:"J,F,M,A,M,J,J,A,S,O,N,D".split(","),kc:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),rc:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),oc:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),uc:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),yc:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),
wc:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),qc:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),vc:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),mc:"S,M,T,W,T,F,S".split(","),tc:"S,M,T,W,T,F,S".split(","),pc:["Q1","Q2","Q3","Q4"],nc:["1st quarter","2nd quarter","3rd quarter","4th quarter"],gc:["AM","PM"],hc:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],xc:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],wb:6,zc:[5,6],xb:5};function nd(a,b,c){ea(a)?(this.a=new Date(a,b||0,c||1),od(this,c||1)):ga(a)?(this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate()),od(this,a.getDate())):(this.a=new Date,this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0))}t=nd.prototype;t.ha=md.wb;t.ia=md.xb;t.p=function(){var a=new nd(this.a);a.ha=this.ha;a.ia=this.ia;return a};t.getFullYear=function(){return this.a.getFullYear()};t.getYear=function(){return this.getFullYear()};t.getMonth=function(){return this.a.getMonth()};
t.getDate=function(){return this.a.getDate()};t.getTime=function(){return this.a.getTime()};t.getUTCHours=function(){return this.a.getUTCHours()};t.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};function pd(a){a=a.getTimezoneOffset();if(a==0)a="Z";else var b=Math.abs(a)/60,c=Math.floor(b),b=(b-c)*60,a=(a>0?"-":"+")+G(c)+":"+G(b);return a}t.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};t.setFullYear=function(a){this.a.setFullYear(a)};t.setMonth=function(a){this.a.setMonth(a)};
t.setDate=function(a){this.a.setDate(a)};
t.add=function(a){if(a.fc||a.Wb){var b=this.getMonth()+a.Wb+a.fc*12,c=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);var d;a:{switch(b){case 1:d=c%4==0&&(c%100!=0||c%400==0)?29:28;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.Kb&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+a.Kb*864E5),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),
this.setDate(a.getDate()),od(this,a.getDate()))};t.Z=function(a,b){return[this.getFullYear(),G(this.getMonth()+1),G(this.getDate())].join(a?"-":"")+(b?pd(this):"")};t.toString=function(){return this.Z()};function od(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}t.valueOf=function(){return this.a.valueOf()};function Ub(a,b,c,d,f,e,h){this.a=ea(a)?new Date(a,b||0,c||1,d||0,f||0,e||0,h||0):new Date(a?a.getTime():C())}F(Ub,nd);t=Ub.prototype;t.getHours=function(){return this.a.getHours()};
t.getMinutes=function(){return this.a.getMinutes()};t.getSeconds=function(){return this.a.getSeconds()};t.getMilliseconds=function(){return this.a.getMilliseconds()};t.getUTCHours=function(){return this.a.getUTCHours()};t.setHours=function(a){this.a.setHours(a)};t.setMinutes=function(a){this.a.setMinutes(a)};t.setSeconds=function(a){this.a.setSeconds(a)};t.setMilliseconds=function(a){this.a.setMilliseconds(a)};t.setUTCHours=function(a){this.a.setUTCHours(a)};
t.add=function(a){nd.prototype.add.call(this,a);a.Sb&&this.setHours(this.a.getHours()+a.Sb);a.Vb&&this.setMinutes(this.a.getMinutes()+a.Vb);a.bc&&this.setSeconds(this.a.getSeconds()+a.bc)};t.Z=function(a,b){var c=nd.prototype.Z.call(this,a);return a?c+" "+G(this.getHours())+":"+G(this.getMinutes())+":"+G(this.getSeconds())+(b?pd(this):""):c+"T"+G(this.getHours())+G(this.getMinutes())+G(this.getSeconds())+(b?pd(this):"")};t.toString=function(){return this.Z()};
t.p=function(){var a=new Ub(this.a);a.ha=this.ha;a.ia=this.ia;return a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function qd(a,b){this.da=[];this.Ac=a;this.Mb=b||k}t=qd.prototype;t.O=q;t.R=q;t.U=0;t.ob=q;t.Gb=q;t.Db=0;t.Sa=function(a,b){rd(this,a,b);this.U--;this.U==0&&this.O&&sd(this)};function rd(a,b,c){a.O=j;a.La=c;a.R=!b;sd(a)}function td(a){if(a.O)a.ob||g(new ud(a)),a.ob=q}function vd(a,b,c,d){a.da.push([b,c,d]);a.O&&sd(a)}function wd(a){return ib(a.da,function(a){return fa(a[1])})}
function sd(a){a.Ma&&a.O&&wd(a)&&(v.clearTimeout(a.Ma),delete a.Ma);a.z&&(a.z.Db--,delete a.z);for(var b=a.La,c=q,d=q;a.da.length&&a.U==0;){var f=a.da.shift(),e=f[0],h=f[1],f=f[2];if(e=a.R?h:e)try{var m=e.call(f||a.Mb,b);if(m!==i)a.R=a.R&&(m==b||m instanceof Error),a.La=b=m;b instanceof qd&&(d=j,a.U++)}catch(o){b=o,a.R=j,wd(a)||(c=j)}}a.La=b;if(d&&a.U)vd(b,pa(a.Sa,a,j),pa(a.Sa,a,q)),b.Gb=j;if(c)a.Ma=v.setTimeout(function(){g(new xd(b))},0)}function ud(a){L.call(this);this.Cc=a}F(ud,L);
ud.prototype.message="Already called";function xd(a){L.call(this);this.Bc=a;this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}F(xd,L);function yd(a,b){var c=b||{},d=c.document||document,f=document.createElement("SCRIPT"),e={mb:f,X:i},h=new qd(zd,e),m=k,o=c.timeout!=k?c.timeout:5E3;if(o>0)m=window.setTimeout(function(){Ad(f,j);var b=new Bd(Cd,"Timeout reached for loading script "+a);td(h);rd(h,q,b)},o),e.X=m;f.onload=f.onreadystatechange=function(){if(!f.readyState||f.readyState=="loaded"||f.readyState=="complete")Ad(f,c.Hb||q,m),td(h),rd(h,j,k)};f.onerror=function(){Ad(f,j,m);var b=new Bd(Dd,"Error while loading script "+a);td(h);
rd(h,q,b)};Pc(f,{type:"text/javascript",charset:"UTF-8",src:a});Ed(d).appendChild(f);return h}function Ed(a){var b=a.getElementsByTagName("HEAD");return!b||b.length==0?a.documentElement:b[0]}function zd(){if(this&&this.mb){var a=this.mb;a&&a.tagName=="SCRIPT"&&Ad(a,j,this.X)}}function Ad(a,b,c){c!=k&&v.clearTimeout(c);a.onload=ca;a.onerror=ca;a.onreadystatechange=ca;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var Dd=0,Cd=1;
function Bd(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);L.call(this,c);this.code=a}F(Bd,L);function dc(a,b){this.$=new xb(a);this.Eb=b?b:"callback";this.X=5E3}var Fd=0;dc.prototype.send=function(a,b,c,d){a=a||k;d=d||"_"+(Fd++).toString(36)+C().toString(36);v._callbacks_||(v._callbacks_={});var f=this.$.p();if(a)for(var e in a)(!a.hasOwnProperty||a.hasOwnProperty(e))&&Mb(f,e,a[e]);b&&(v._callbacks_[d]=Kd(d,b),Mb(f,this.Eb,"_callbacks_."+d));b=yd(f.toString(),{timeout:this.X,Hb:j});vd(b,k,Ld(d,a,c),i);return{Fc:d,Dc:b}};function Ld(a,b,c){return function(){Md(a,q);c&&c(b)}}
function Kd(a,b){return function(c){Md(a,j);b.apply(i,arguments)}}function Md(a,b){v._callbacks_[a]&&(b?delete v._callbacks_[a]:v._callbacks_[a]=ca)};H||I&&K("1.9.3");function Yb(a,b){this.ka=a||1;this.Y=b||Nd;this.ua=pa(this.dc,this);this.Ha=C()}F(Yb,hd);Yb.prototype.enabled=q;var Nd=v.window;t=Yb.prototype;t.C=k;t.dc=function(){if(this.enabled){var a=C()-this.Ha;if(a>0&&a<this.ka*0.8)this.C=this.Y.setTimeout(this.ua,this.ka-a);else if(this.dispatchEvent($b),this.enabled)this.C=this.Y.setTimeout(this.ua,this.ka),this.Ha=C()}};t.start=function(){this.enabled=j;if(!this.C)this.C=this.Y.setTimeout(this.ua,this.ka),this.Ha=C()};
t.stop=function(){this.enabled=q;if(this.C)this.Y.clearTimeout(this.C),this.C=k};t.j=function(){Yb.W.j.call(this);this.stop();delete this.Y};var $b="tick";function Od(a){this.Ec=a||Nc();P.call(this)}F(Od,P);t=Od.prototype;t.Lb=k;t.Pb=k;t.Fb=k;t.set=function(a,b,c,d){P.prototype.set.call(this,a,b);if(c)this.Lb=a;if(d)this.Fb=a;return this};function $(a,b,c,d){return a.set(b.key,b.caption,c,d)}t.cb=aa("Pb");var Pd={key:"ok",caption:"Tamam"},Qd={key:"cancel",caption:"Vazge\u00e7"},Rd={key:"yes",caption:"Evet"},Sd={key:"no",caption:"Hay\u0131r"},Td={key:"save",caption:"Kaydet"},Ud={key:"continue",caption:"Devam Et"};
typeof document!="undefined"&&($(new Od,Pd,j,j),$($(new Od,Pd,j),Qd,q,j),$($(new Od,Rd,j),Sd,q,j),$($($(new Od,Rd),Sd,j),Qd,q,j),$($($(new Od,Ud),Td),Qd,j,j));Fc("goog.net.XhrIo");window.onload=function(){new kd;new xb(window.location);E("HandsomeWidget",T);E("HandsomeWidget.prototype.AddEvent",T.prototype.vb);E("HandsomeWidget.prototype.RemoveEvent",T.prototype.zb);E("HandsomeWidget.prototype.GetRowColumns",T.prototype.yb);E("HandsomeWidget.prototype.StopListener",T.prototype.Bb);E("HandsomeWidget.prototype.StartListener",T.prototype.Ab);console.info("HandsomeWidget 1.1.0");console.info("HandsomeWidget.prototype.AddEvent");console.info("HandsomeWidget.prototype.RemoveEvent");
console.info("HandsomeWidget.prototype.GetRowColumns");console.info("HandsomeWidget.prototype.StopListener");console.info("HandsomeWidget.prototype.StartListener")};})()
