(function(){function g(a){throw a;}var i=void 0,j=true,l=null,q=false;function aa(a){return function(){return this[a]}}var t,v=this;function ba(a){for(var a=a.split("."),b=v,c;c=a.shift();)if(b[c]!=l)b=b[c];else return l;return b}function ca(){}
function da(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function w(a){return da(a)=="array"}function y(a){var b=da(a);return b=="array"||b=="object"&&typeof a.length=="number"}function z(a){return typeof a=="string"}function ea(a){return typeof a=="number"}function fa(a){return da(a)=="function"}function ga(a){var b=typeof a;return b=="object"&&a!=l||b=="function"}function ha(a){return a[ia]||(a[ia]=++ja)}
var ia="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ja=0;function ka(a,b,c){return a.call.apply(a.bind,arguments)}function oa(a,b,c){a||g(Error());if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function pa(a,b,c){pa=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ka:oa;return pa.apply(l,arguments)}var C=Date.now||function(){return+new Date};function E(a,b){var c=a.split("."),d=v;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==i?d[f]=b:d=d[f]?d[f]:d[f]={}}function F(a,b){function c(){}c.prototype=b.prototype;a.X=b.prototype;a.prototype=new c;a.prototype.constructor=a};function qa(a,b){for(var c=1;c<arguments.length;c++)var d=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}function ra(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function sa(a,b){var c=String(a).toLowerCase(),d=String(b).toLowerCase();return c<d?-1:c==d?0:1}var ta=/^[a-zA-Z0-9\-_.!~*'()]*$/;function ua(a){a=String(a);return!ta.test(a)?encodeURIComponent(a):a}
function va(a){if(!wa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(xa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ya,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(za,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(Aa,"&quot;"));return a}var xa=/&/g,ya=/</g,za=/>/g,Aa=/\"/g,wa=/[&<>\"]/;function G(a){var a=String(a),b=a.indexOf(".");if(b==-1)b=a.length;b=Math.max(0,2-b);return Array(b+1).join("0")+a}function Ba(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Ca,Da,Ga,Ha;function Ia(){return v.navigator?v.navigator.userAgent:l}Ha=Ga=Da=Ca=q;var Ja;if(Ja=Ia()){var Ka=v.navigator;Ca=Ja.indexOf("Opera")==0;Da=!Ca&&Ja.indexOf("MSIE")!=-1;Ga=!Ca&&Ja.indexOf("WebKit")!=-1;Ha=!Ca&&!Ga&&Ka.product=="Gecko"}var La=Ca,H=Da,I=Ha,J=Ga,Ma=v.navigator,Na=(Ma&&Ma.platform||"").indexOf("Mac")!=-1,Oa;
a:{var Pa="",Qa;if(La&&v.opera)var Sa=v.opera.version,Pa=typeof Sa=="function"?Sa():Sa;else if(I?Qa=/rv\:([^\);]+)(\)|;)/:H?Qa=/MSIE\s+([^\);]+)(\)|;)/:J&&(Qa=/WebKit\/(\S+)/),Qa)var Ta=Qa.exec(Ia()),Pa=Ta?Ta[1]:"";if(H){var Ua,Va=v.document;Ua=Va?Va.documentMode:i;if(Ua>parseFloat(Pa)){Oa=String(Ua);break a}}Oa=Pa}var Wa={};
function K(a){var b;if(!(b=Wa[a])){b=0;for(var c=ra(String(Oa)).split("."),d=ra(String(a)).split("."),f=Math.max(c.length,d.length),e=0;b==0&&e<f;e++){var h=c[e]||"",m=d[e]||"",n=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(h)||["","",""],o=k.exec(m)||["","",""];if(r[0].length==0&&o[0].length==0)break;b=Ba(r[1].length==0?0:parseInt(r[1],10),o[1].length==0?0:parseInt(o[1],10))||Ba(r[2].length==0,o[2].length==0)||Ba(r[2],o[2])}while(b==0)}b=Wa[a]=b>=0}return b}var Xa={};
function Ya(){return Xa[9]||(Xa[9]=H&&!!document.documentMode&&document.documentMode>=9)};function L(a){Error.captureStackTrace?Error.captureStackTrace(this,L):this.stack=Error().stack||"";if(a)this.message=String(a)}F(L,Error);L.prototype.name="CustomError";function Za(a,b){b.unshift(a);L.call(this,qa.apply(l,b));b.shift();this.Lc=a}F(Za,L);Za.prototype.name="AssertionError";function $a(a,b){g(new Za("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var ab=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function M(a,b){for(var c in a)b.call(i,a[c],c,a)}function bb(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function cb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function db(a,b){for(var c=y(b),d=c?b:arguments,c=c?0:1;c<d.length;c++)if(a=a[d[c]],a===i)break;return a}function eb(a,b,c){a[b]=c}var fb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");
function gb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<fb.length;e++)c=fb[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var N=Array.prototype,hb=N.indexOf?function(a,b,c){return N.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:c<0?Math.max(0,a.length+c):c;if(z(a))return!z(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},O=N.forEach?function(a,b,c){N.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},ib=N.some?function(a,b,c){return N.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(""):a,
e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return j;return q};function jb(a){return N.concat.apply(N,arguments)}function kb(a,b){N.sort.call(a,b||lb)}function mb(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||lb;kb(a,function(a,b){return d(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value}function lb(a,b){return a>b?1:a<b?-1:0};var nb="StopIteration"in v?v.StopIteration:Error("StopIteration");function ob(){}ob.prototype.next=function(){g(nb)};ob.prototype.ra=function(){return this};function pb(a){if(a instanceof ob)return a;if(typeof a.ra=="function")return a.ra(q);if(y(a)){var b=0,c=new ob;c.next=function(){for(;;)if(b>=a.length&&g(nb),b in a)return a[b++];else b++};return c}g(Error("Not implemented"))}
function qb(a,b){if(y(a))try{O(a,b,i)}catch(c){c!==nb&&g(c)}else{a=pb(a);try{for(;;)b.call(i,a.next(),i,a)}catch(d){d!==nb&&g(d)}}};function rb(a){if(typeof a.z=="function")return a.z();if(z(a))return a.split("");if(y(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return bb(a)}function sb(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(y(a)||z(a))O(a,b,c);else{var d;if(typeof a.r=="function")d=a.r();else if(typeof a.z!="function")if(y(a)||z(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else d=cb(a);else d=i;for(var f=rb(a),e=f.length,h=0;h<e;h++)b.call(c,f[h],d&&d[h],a)}};function P(a,b){this.i={};this.e=[];var c=arguments.length;if(c>1){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof P?(c=a.r(),d=a.z()):(c=cb(a),d=bb(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}t=P.prototype;t.b=0;t.ca=0;t.eb=aa("b");t.z=function(){tb(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.i[this.e[b]]);return a};t.r=function(){tb(this);return this.e.concat()};t.q=function(a){return ub(this.i,a)};
t.clear=function(){this.i={};this.ca=this.b=this.e.length=0};t.remove=function(a){return ub(this.i,a)?(delete this.i[a],this.b--,this.ca++,this.e.length>2*this.b&&tb(this),j):q};function tb(a){if(a.b!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];ub(a.i,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.b!=a.e.length){for(var f={},c=b=0;b<a.e.length;)d=a.e[b],ub(f,d)||(a.e[c++]=d,f[d]=1),b++;a.e.length=c}}t.get=function(a,b){return ub(this.i,a)?this.i[a]:b};
t.set=function(a,b){ub(this.i,a)||(this.b++,this.e.push(a),this.ca++);this.i[a]=b};t.p=function(){return new P(this)};t.ra=function(a){tb(this);var b=0,c=this.e,d=this.i,f=this.ca,e=this,h=new ob;h.next=function(){for(;;){f!=e.ca&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(nb);var h=c[b++];return a?h:d[h]}};return h};function ub(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function vb(a,b){var c;a instanceof vb?(this.L(b==l?a.k:b),wb(this,a.s),zb(this,a.ba),Ab(this,a.v),Bb(this,a.H),Cb(this,a.B),Db(this,a.l.p()),Eb(this,a.Q)):a&&(c=String(a).match(ab))?(this.L(!!b),wb(this,c[1]||"",j),zb(this,c[2]||"",j),Ab(this,c[3]||"",j),Bb(this,c[4]),Cb(this,c[5]||"",j),Db(this,c[6]||"",j),Eb(this,c[7]||"",j)):(this.L(!!b),this.l=new Fb(l,this,this.k))}t=vb.prototype;t.s="";t.ba="";t.v="";t.H=l;t.B="";t.Q="";t.Xb=q;t.k=q;
t.toString=function(){if(this.h)return this.h;var a=[];this.s&&a.push(Gb(this.s,Hb),":");this.v&&(a.push("//"),this.ba&&a.push(Gb(this.ba,Hb),"@"),a.push(z(this.v)?encodeURIComponent(this.v):l),this.H!=l&&a.push(":",String(this.H)));this.B&&(this.v&&this.B.charAt(0)!="/"&&a.push("/"),a.push(Gb(this.B,this.B.charAt(0)=="/"?Ib:Jb)));var b=String(this.l);b&&a.push("?",b);this.Q&&a.push("#",Gb(this.Q,Kb));return this.h=a.join("")};
t.p=function(){var a=this.s,b=this.ba,c=this.v,d=this.H,f=this.B,e=this.l.p(),h=this.Q,m=new vb(l,this.k);a&&wb(m,a);b&&zb(m,b);c&&Ab(m,c);d&&Bb(m,d);f&&Cb(m,f);e&&Db(m,e);h&&Eb(m,h);return m};function wb(a,b,c){Q(a);delete a.h;a.s=c?b?decodeURIComponent(b):"":b;if(a.s)a.s=a.s.replace(/:$/,"")}function zb(a,b,c){Q(a);delete a.h;a.ba=c?b?decodeURIComponent(b):"":b}function Ab(a,b,c){Q(a);delete a.h;a.v=c?b?decodeURIComponent(b):"":b}
function Bb(a,b){Q(a);delete a.h;b?(b=Number(b),(isNaN(b)||b<0)&&g(Error("Bad port number "+b)),a.H=b):a.H=l}function Cb(a,b,c){Q(a);delete a.h;a.B=c?b?decodeURIComponent(b):"":b}function Db(a,b,c){Q(a);delete a.h;b instanceof Fb?(a.l=b,a.l.aa=a,a.l.L(a.k)):(c||(b=Gb(b,Lb)),a.l=new Fb(b,a,a.k))}function Mb(a,b,c){Q(a);delete a.h;w(c)||(c=[String(c)]);a=a.l;R(a);Nb(a);b=S(a,b);if(a.q(b)){var d=a.d.get(b);w(d)?a.b-=d.length:a.b--}c.length>0&&(a.d.set(b,c),a.b+=c.length)}
function Eb(a,b,c){Q(a);delete a.h;a.Q=c?b?decodeURIComponent(b):"":b}function Q(a){a.Xb&&g(Error("Tried to modify a read-only Uri"))}t.L=function(a){this.k=a;this.l&&this.l.L(a);return this};var Ob=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;function Gb(a,b){var c=l;z(a)&&(c=a,Ob.test(c)||(c=encodeURI(a)),c.search(b)>=0&&(c=c.replace(b,Pb)));return c}function Pb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Hb=/[#\/\?@]/g,Jb=/[\#\?:]/g,Ib=/[\#\?]/g,Lb=/[\#\?@]/g,Kb=/#/g;
function Fb(a,b,c){this.o=a||l;this.aa=b||l;this.k=!!c}function R(a){if(!a.d&&(a.d=new P,a.b=0,a.o))for(var b=a.o.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=l,e=l;d>=0?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=S(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}t=Fb.prototype;t.d=l;t.b=l;t.eb=function(){R(this);return this.b};
t.add=function(a,b){R(this);Nb(this);a=S(this,a);if(this.q(a)){var c=this.d.get(a);w(c)?c.push(b):this.d.set(a,[c,b])}else this.d.set(a,b);this.b++;return this};t.remove=function(a){R(this);a=S(this,a);if(this.d.q(a)){Nb(this);var b=this.d.get(a);w(b)?this.b-=b.length:this.b--;return this.d.remove(a)}return q};t.clear=function(){Nb(this);this.d&&this.d.clear();this.b=0};t.q=function(a){R(this);a=S(this,a);return this.d.q(a)};
t.r=function(){R(this);for(var a=this.d.z(),b=this.d.r(),c=[],d=0;d<b.length;d++){var f=a[d];if(w(f))for(var e=0;e<f.length;e++)c.push(b[d]);else c.push(b[d])}return c};t.z=function(a){R(this);var b=[];if(a)a=S(this,a),this.q(a)&&(b=jb(b,this.d.get(a)));else for(var a=this.d.z(),c=0;c<a.length;c++)b=jb(b,a[c]);return b};t.set=function(a,b){R(this);Nb(this);a=S(this,a);if(this.q(a)){var c=this.d.get(a);w(c)?this.b-=c.length:this.b--}this.d.set(a,b);this.b++;return this};
t.get=function(a,b){R(this);a=S(this,a);if(this.q(a)){var c=this.d.get(a);return w(c)?c[0]:c}else return b};t.toString=function(){if(this.o)return this.o;if(!this.d)return"";for(var a=[],b=0,c=this.d.r(),d=0;d<c.length;d++){var f=c[d],e=ua(f),f=this.d.get(f);if(w(f))for(var h=0;h<f.length;h++)b>0&&a.push("&"),a.push(e),f[h]!==""&&a.push("=",ua(f[h])),b++;else b>0&&a.push("&"),a.push(e),f!==""&&a.push("=",ua(f)),b++}return this.o=a.join("")};
function Nb(a){delete a.ya;delete a.o;a.aa&&delete a.aa.h}t.p=function(){var a=new Fb;if(this.ya)a.ya=this.ya;if(this.o)a.o=this.o;if(this.d)a.d=this.d.p();return a};function S(a,b){var c=String(b);a.k&&(c=c.toLowerCase());return c}t.L=function(a){a&&!this.k&&(R(this),Nb(this),sb(this.d,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.add(d,a))},this));this.k=a};function Qb(a){this.dataset=a}function Rb(a,b){var c={ms:0,sum:0,timeslot:{},columns:b},d=C();console.log("makina.Dataset.prototype.Sum");var f=0,e={c:0};O(a.dataset,function(c){M(c,function(c,d,h){O(b,function(b){b.lastIndexOf("timeslot",0)==0?e[b]=a.Pa([e[b],h[b]]):isNaN(h[b])||(f+=h[b])})})});O(b,function(a){e.c+=e[a].c});c.sum=f;c.timeslot=e;d=C()-d;c.ms=d;return c}
function Sb(a,b,c,d){function f(a){var c=j;O(b,function(b,f){d[f]!=l&&a[b]!=d[f]&&(c=q)});return c}function e(a){var b=q,c;for(c in n){var d=n[c];if(d.val==a.val)n[c].item=h(d.item,a.item),b=j}b||n.push(a)}function h(b,d){O(c,function(c){(c in b?b[c]:i)==i?b[c]=d[c]:c.lastIndexOf("timeslot",0)==0?b[c]=a.Pa([b[c],d[c]]):ea(b[c])?b[c]+=d[c]:b[c]=""});return b}var m=b,m=m.concat(c);d!==i||(d=l);var n=[],k=C();O(a.dataset,function(a){var c={groups:{key:"",val:""},item:{}},h=[];O(b,function(b){b=db(a,
b);h.push(b)});c.val=h.join("|");var k={};O(m,function(b){k[b]=a[b]});c.item=k;d!=l?f(k)&&e(c):e(c)});var r=[],o;for(o in n)r.push(n[o].item);mb(r,function(a,c){return sa(a[b[0]],c[b[0]])});return{ms:C()-k,columns:m,rows:r}}
function Tb(a,b){function c(a,b){var c=q;O(d[a],function(a){a==b&&(c=j)});c||d[a].push(b)}var b=b.sort(),d={},f=C();O(b,function(a){d[a]=[]});console.log("makina.Dataset.prototype.GetColumnValues");O(a.dataset,function(a){O(b,function(b){c(b,a[b])})});O(b,function(a){mb(d[a],function(a,b){return sa(a,b)})});var f=C()-f,e={};e.columns=b;e.rows=d;e.ms=f;return e}
Qb.prototype.Pa=function(a){var b={c:0};O(a,function(a){M(a,function(a,c){var e=0;a.c>0&&(e=a.c);c in b?b[c].c+=e:eb(b,c,{c:e});b.c+=e;M(a,function(a,d){d!="c"&&(d in b[c]?b[c][d].c+=a.c:eb(b[c],d,{c:a.c}));M(a,function(a,e){e!="c"&&(e in b[c][d]?b[c][d][e].c+=a.c:eb(b[c][d],e,{c:a.c}));M(a,function(a,h){h!="c"&&(h in b[c][d][e]?b[c][d][e][h].c+=a.c:b[c][d][e][h]={c:a.c})})})})})});return b};function T(a,b){this.options=a;this.Ha=j;this.w=a.fetchOptions;this.t="";if(b!=i)this.t=b;if(this.t!="")this.Aa=z(this.t)?document.getElementById(this.t):this.t;this.Fb=this.options.url;this.M=this.options.refreshTime*1E3;this.Qa=this.options.requestJsonData;this.ua=this.options.responseSuccessCallBack;this.ta=this.options.responseErrorCallBack;this.sa=this.options.responseColumnsCallBack;this.dc=[];this.u=[];this.N=[];this.Ra=Math.round((new Ub(1999,1,1,10,10,10)).getTime()/1E3);this.ha=new Qb(this.u);
U(this,"Start Widget","blue");Vb(this)}t=T.prototype;t.xb=function(a,b){var c=q;O(this.w,function(b){b.id==a.id&&(c=j)});if(!c)fa(b)&&(a.fetchCallBack=b),this.w.push(a);return!c};t.Cb=function(a){var b=q,c=[];O(this.w,function(d){d.id==a?b=j:c.push(d)});if(b)this.w=c;return b};t.Bb=function(){return{columns:this.N}};t.Ab=function(){var a={};a.columns=this.N;a.rows=this.u;return a};t.Eb=function(){this.Ha=q;return j};t.Db=function(){return this.Ha=j};
function Wb(a,b){var c=[];O(b,function(b){O(a.N,function(a){a.cname==b&&c.push(a)})});return c}function U(a,b,c){var d=new Ub,b=d.$(j)+"."+d.getMilliseconds()+" : "+b,d="black";c!=i&&(d=c);console.log(b);try{a.t!=""&&a.Aa!=i&&a.Aa.appendChild(Xb("<div style='color:"+d+" ' >"+b+"</div>"))}catch(f){}}
function Yb(a){if(!ea(a.M))a.M=0;if(a.M>0)a.m==l||a.m==i?(U(a,"Create Timer and Start Timer "+a.M/1E3+" ms"),a.m=new Zb(a.M),a.m.start(),$b(a.m,ac,function(){a.Ha&&Vb(a)})):(U(a,"Start Timer..."),a.m.start())}
function bc(a,b){a.dc=b;a.N=b.columns;cc(a,b.rows);var c={};c.columns=a.N;c.rows=a.u;a.ua!=l&&a.ua&&a.ua(c);a.sa!=l&&a.sa&&a.sa(c);a.ha.dataset=a.u;C();U(a,"Fetch Event Options Started","red");var d=0,f=0,e=q;if(a.w!=l)f=a.w.length;ea(f)||(f=0);if(f>0)var h=setInterval(function(){if(!e){e=j;var b=a.w[d],c=C();U(a,"Start "+b.name+" ProcessFetchItems","green");if(b.type=="sum"){var k=Rb(a.ha,b.columns);k.columns=Wb(a,k.columns);b.fetchCallBack!=l&&b.fetchCallBack(k)}else if(b.type=="groupby")k=Sb(a.ha,
b.byColumns,b.columns,b.byValues),k.columns=Wb(a,k.columns),b.fetchCallBack!=l&&b.fetchCallBack(k);else if(b.type=="keyvalues")console.log("Call get key Values Array"),k=Tb(a.ha,b.byColumns),k.columns=Wb(a,k.columns),b.fetchCallBack!=l&&b.fetchCallBack(k);c=C()-c;U(a,"End "+b.name+" ProcessFetchItems ms="+c,"green");++d==f&&(Yb(a),clearInterval(h));e=q}},200);else Yb(a);U(a,"Fetch Event Options Endddddddddd","red")}function dc(a){a.m==l||a.m==i||(a.m.stop(),U(a,"Stop Timer"))}
function Vb(a){a.Qa.utcTime=a.Ra;var b=a.Fb+"?request="+ec(a.Qa),b=new fc(b);b.Y=45E3;try{if(a.t!="")a.Aa.innerHTML=""}catch(c){}U(a,"Request Data With JSONP","blue");dc(a);var d=C();b.send({},function(b){var c=C()-d;U(a,"Response JSONP Request ms="+c);bc(a,b)},function(b){a.m.start();a.ta!=l&&a.ta&&a.ta(b)})}
function cc(a,b){if(b.length!=0){var c=new Ub;a.Ra=Math.round(c.getTime()/1E3)}U(a,"Start decode code ","yellow");c=C();O(b,function(c,f){M(c,function(a,c){if(c.lastIndexOf("timeslot",0)==0){for(var d=b[f],n=gc,k=b[f][c],r="",o,B,A,s,p,D=0,k=k.replace(/[^A-Za-z0-9\+\/\=]/g,"");D<k.length;)o="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(D++)),B="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(D++)),s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(D++)),
p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(D++)),o=o<<2|B>>4,B=(B&15)<<4|s>>2,A=(s&3)<<6|p,r+=String.fromCharCode(o),s!=64&&(r+=String.fromCharCode(B)),p!=64&&(r+=String.fromCharCode(A));k="";for(o=D=p=s=0;s<r.length;)p=r.charCodeAt(s),p<128?(k+=String.fromCharCode(p),s++):p>191&&p<224?(D=r.charCodeAt(s+1),k+=String.fromCharCode((p&31)<<6|D&63),s+=2):(D=r.charCodeAt(s+1),o=r.charCodeAt(s+2),k+=String.fromCharCode((p&15)<<12|(D&63)<<6|o&63),s+=3);d[c]=n(k)}});
hc(a,c)});U(a,"End of decode code ms="+(C()-c),"yellow")}function hc(a,b){var c=q,d={};try{O(a.u,function(e,f){e._rowKey==b._rowKey&&(a.u[f]=b,c=j,g(d))})}catch(f){}c||a.u.push(b)};function ic(a){return jc(a||arguments.callee.caller,[])}
function jc(a,b){var c=[];if(hb(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(kc(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){f>0&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=kc(e))?e:"[fn]";break;default:e=typeof e}e.length>40&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(jc(a.caller,b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function kc(a){if(lc[a])return lc[a];a=String(a);if(!lc[a]){var b=/function ([^\(]+)/.exec(a);lc[a]=b?b[1]:"[Anonymous]"}return lc[a]}var lc={};function mc(){}mc.prototype.Za=q;mc.prototype.F=function(){if(!this.Za)this.Za=j,this.j()};mc.prototype.j=function(){this.Rb&&nc.apply(l,this.Rb)};function nc(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];y(d)?nc.apply(l,d):d&&typeof d.F=="function"&&d.F()}};function oc(a,b){this.kb=b;this.R=[];a>this.kb&&g(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.R.push(this.ga())}F(oc,mc);t=oc.prototype;t.Va=l;t.Ya=l;function pc(a,b){a.R.length<a.kb?a.R.push(b):a.za(b)}t.ga=function(){return this.Va?this.Va():{}};t.za=function(a){if(this.Ya)this.Ya(a);else if(ga(a))if(fa(a.F))a.F();else for(var b in a)delete a[b]};t.j=function(){oc.X.j.call(this);for(var a=this.R;a.length;)this.za(a.pop());delete this.R};function qc(a,b,c,d,f){this.reset(a,b,c,d,f)}qc.prototype.fc=0;qc.prototype.cb=l;qc.prototype.bb=l;var rc=0;qc.prototype.reset=function(a,b,c,d,f){this.fc=typeof f=="number"?f:rc++;this.Oc=d||C();this.T=a;this.$b=b;this.Kc=c;delete this.cb;delete this.bb};qc.prototype.pb=function(a){this.T=a};function W(a){this.ac=a}W.prototype.A=l;W.prototype.T=l;W.prototype.xa=l;W.prototype.gb=l;function sc(a,b){this.name=a;this.value=b}sc.prototype.toString=aa("name");var tc=new sc("INFO",800),uc=new sc("CONFIG",700);t=W.prototype;t.getParent=aa("A");t.pb=function(a){this.T=a};function vc(a){if(a.T)return a.T;if(a.A)return vc(a.A);$a("Root logger has no level set.");return l}
t.log=function(a,b,c){if(a.value>=vc(this).value){a=this.Ub(a,b,c);b="log:"+a.$b;v.console&&(v.console.timeStamp?v.console.timeStamp(b):v.console.markTimeline&&v.console.markTimeline(b));v.msWriteProfilerMark&&v.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.gb)for(var f=0,e=i;e=c.gb[f];f++)e(d);b=b.getParent()}}};
t.Ub=function(a,b,c){var d=new qc(a,String(b),this.ac);if(c){d.cb=c;var f;var e=arguments.callee.caller;try{var h;var m=ba("window.location.href");if(z(c))h={message:c,name:"Unknown error",lineNumber:"Not available",fileName:m,stack:"Not available"};else{var n,k,r=q;try{n=c.lineNumber||c.Jc||"Not available"}catch(o){n="Not available",r=j}try{k=c.fileName||c.filename||c.sourceURL||m}catch(B){k="Not available",r=j}h=r||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:n,
fileName:k,stack:c.stack||"Not available"}:c}f="Message: "+va(h.message)+'\nUrl: <a href="view-source:'+h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+va(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+va(ic(e)+"-> ")}catch(A){f="Exception trying to expose exception! You win, we lose. "+A}d.bb=f}return d};t.info=function(a,b){this.log(tc,a,b)};var Fc={},Gc=l;
function Hc(a){Gc||(Gc=new W(""),Fc[""]=Gc,Gc.pb(uc));var b;if(!(b=Fc[a])){b=new W(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Hc(a.substr(0,c));if(!c.xa)c.xa={};c.xa[d]=b;b.A=c;Fc[a]=b}return b};function Ic(){this.O=[];this.Ka=new P;this.ub=this.vb=this.wb=this.rb=0;this.W=new P;this.Ta=this.tb=0;this.mb=1;this.Ba=new oc(0,4E3);this.Ba.ga=function(){return new Jc};this.sb=new oc(0,50);this.sb.ga=function(){return new Kc};var a=this;this.Ga=new oc(0,2E3);this.Ga.ga=function(){return String(a.mb++)};this.Ga.za=function(){};this.Qb=3}function Kc(){this.Oa=this.time=this.fa=0}
Kc.prototype.toString=function(){var a=[];a.push(this.type," ",this.fa," (",Math.round(this.time*10)/10," ms)");this.Oa&&a.push(" [VarAlloc = ",this.Oa,"]");return a.join("")};function Jc(){}function Lc(a,b,c,d){var f=[];c==-1?f.push("    "):f.push(Mc(a.ab-c));f.push(" ",Nc(a.ab-b));a.Ca==0?f.push(" Start        "):a.Ca==1?(f.push(" Done "),f.push(Mc(a.Nc-a.startTime)," ms ")):f.push(" Comment      ");f.push(d,a);a.hc>0&&f.push("[VarAlloc ",a.hc,"] ");return f.join("")}
Jc.prototype.toString=function(){return this.type==l?this.Lb:"["+this.type+"] "+this.Lb};Ic.prototype.reset=function(a){this.Qb=a;for(a=0;a<this.O.length;a++){var b=this.Ba.id;b&&pc(this.Ga,b);pc(this.Ba,this.O[a])}this.O.length=0;this.Ka.clear();this.rb=C();this.Ta=this.tb=this.ub=this.vb=this.wb=0;b=this.W.r();for(a=0;a<b.length;a++){var c=this.W.get(b[a]);c.fa=0;c.time=0;c.Oa=0;pc(this.sb,c)}this.W.clear()};
Ic.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.O.length;d++){var f=this.O[d];f.Ca==1&&c.pop();a.push(" ",Lc(f,this.rb,b,c.join("")));b=f.ab;a.push("\n");f.Ca==0&&c.push("|  ")}if(this.Ka.eb()!=0){var e=C();a.push(" Unstopped timers:\n");qb(this.Ka,function(b){a.push("  ",b," (",e-b.startTime," ms, started at ",Nc(b.startTime),")\n")})}b=this.W.r();for(d=0;d<b.length;d++)c=this.W.get(b[d]),c.fa>1&&a.push(" TOTAL ",c,"\n");a.push("Total tracers created ",this.tb,"\n","Total comments created ",
this.Ta,"\n","Overhead start: ",this.wb," ms\n","Overhead end: ",this.vb," ms\n","Overhead comment: ",this.ub," ms\n");return a.join("")};function Mc(a){var a=Math.round(a),b="";a<1E3&&(b=" ");a<100&&(b="  ");a<10&&(b="   ");return b+a}function Nc(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new Ic;var Oc;!H||Ya();!I&&!H||H&&Ya()||I&&K("1.9.1");H&&K("9");function Pc(a){return a?new Qc(a.nodeType==9?a:a.ownerDocument||a.document):Oc||(Oc=new Qc)}function Rc(a,b){M(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in Sc?a.setAttribute(Sc[d],b):d.lastIndexOf("aria-",0)==0?a.setAttribute(d,b):a[d]=b})}var Sc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Qc(a){this.$a=a||v.document||document}Qc.prototype.fb=function(a){return z(a)?this.$a.getElementById(a):a};Qc.prototype.createElement=function(a){return this.$a.createElement(a)};Qc.prototype.appendChild=function(a,b){a.appendChild(b)};function Tc(){}var Uc=0;t=Tc.prototype;t.key=0;t.K=q;t.Sa=q;t.ka=function(a,b,c,d,f,e){fa(a)?this.ib=j:a&&a.handleEvent&&fa(a.handleEvent)?this.ib=q:g(Error("Invalid listener argument"));this.U=a;this.nb=b;this.src=c;this.type=d;this.capture=!!f;this.Fa=e;this.Sa=q;this.key=++Uc;this.K=q};t.handleEvent=function(a){return this.ib?this.U.call(this.Fa||this.src,a):this.U.handleEvent.call(this.U,a)};!H||Ya();var Vc=!H||Ya(),Wc=H&&!K("8");!J||K("528");I&&K("1.9b")||H&&K("8")||La&&K("9.5")||J&&K("528");I&&!K("8")||H&&K("9");function X(a,b){this.type=a;this.currentTarget=this.target=b}F(X,mc);t=X.prototype;t.j=function(){delete this.type;delete this.target;delete this.currentTarget};t.I=q;t.Xa=q;t.qa=j;t.preventDefault=function(){this.Xa=j;this.qa=q};function Xc(a){Xc[" "](a);return a}Xc[" "]=ca;function Yc(a,b){a&&this.ka(a,b)}F(Yc,X);t=Yc.prototype;t.target=l;t.relatedTarget=l;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=q;t.altKey=q;t.shiftKey=q;t.metaKey=q;t.cc=q;t.Da=l;
t.ka=function(a,b){var c=this.type=a.type;X.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(I){var f;a:{try{Xc(d.nodeName);f=j;break a}catch(e){}f=q}f||(d=l)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=J||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=J||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.cc=Na?a.metaKey:a.ctrlKey;this.state=a.state;this.Da=a;a.Xa&&this.preventDefault();delete this.I};
t.preventDefault=function(){Yc.X.preventDefault.call(this);var a=this.Da;if(a.preventDefault)a.preventDefault();else if(a.returnValue=q,Wc)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};t.j=function(){Yc.X.j.call(this);this.relatedTarget=this.currentTarget=this.target=this.Da=l};var Zc={},Y={},Z={},$c={};
function $b(a,b,c,d,f){if(b)if(w(b))for(var e=0;e<b.length;e++)$b(a,b[e],c,d,f);else{var d=!!d,h=Y;b in h||(h[b]={b:0,g:0});h=h[b];d in h||(h[d]={b:0,g:0},h.b++);var h=h[d],m=ha(a),n;h.g++;if(h[m]){n=h[m];for(e=0;e<n.length;e++)if(h=n[e],h.U==c&&h.Fa==f){if(h.K)break;return}}else n=h[m]=[],h.b++;e=ad();e.src=a;h=new Tc;h.ka(c,e,a,b,d,f);c=h.key;e.key=c;n.push(h);Zc[c]=h;Z[m]||(Z[m]=[]);Z[m].push(h);a.addEventListener?(a==v||!a.Wa)&&a.addEventListener(b,e,d):a.attachEvent(b in $c?$c[b]:$c[b]="on"+
b,e)}else g(Error("Invalid event type"))}function ad(){var a=bd,b=Vc?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function cd(a,b,c,d,f){if(w(b))for(var e=0;e<b.length;e++)cd(a,b[e],c,d,f);else{d=!!d;a:{e=Y;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ha(a),e[a]))){a=e[a];break a}a=l}if(a)for(e=0;e<a.length;e++)if(a[e].U==c&&a[e].capture==d&&a[e].Fa==f){dd(a[e].key);break}}}
function dd(a){if(Zc[a]){var b=Zc[a];if(!b.K){var c=b.src,d=b.type,f=b.nb,e=b.capture;c.removeEventListener?(c==v||!c.Wa)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in $c?$c[d]:$c[d]="on"+d,f);c=ha(c);f=Y[d][e][c];if(Z[c]){var h=Z[c],m=hb(h,b);m>=0&&N.splice.call(h,m,1);h.length==0&&delete Z[c]}b.K=j;f.lb=j;ed(d,e,c,f);delete Zc[a]}}}
function ed(a,b,c,d){if(!d.ma&&d.lb){for(var f=0,e=0;f<d.length;f++)d[f].K?d[f].nb.src=l:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.lb=q;e==0&&(delete Y[a][b][c],Y[a][b].b--,Y[a][b].b==0&&(delete Y[a][b],Y[a].b--),Y[a].b==0&&delete Y[a])}}function fd(a){var b,c=0,d=b==l;b=!!b;if(a==l)M(Z,function(a){for(var e=a.length-1;e>=0;e--){var f=a[e];if(d||b==f.capture)dd(f.key),c++}});else if(a=ha(a),Z[a])for(var a=Z[a],f=a.length-1;f>=0;f--){var e=a[f];if(d||b==e.capture)dd(e.key),c++}}
function gd(a,b,c,d,f){var e=1,b=ha(b);if(a[b]){a.g--;a=a[b];a.ma?a.ma++:a.ma=1;try{for(var h=a.length,m=0;m<h;m++){var n=a[m];n&&!n.K&&(e&=hd(n,f)!==q)}}finally{a.ma--,ed(c,d,b,a)}}return Boolean(e)}function hd(a,b){var c=a.handleEvent(b);a.Sa&&dd(a.key);return c}
function bd(a,b){if(!Zc[a])return j;var c=Zc[a],d=c.type,f=Y;if(!(d in f))return j;var f=f[d],e,h;if(!Vc){e=b||ba("window.event");var m=j in f,n=q in f;if(m){if(e.keyCode<0||e.returnValue!=i)return j;a:{var k=q;if(e.keyCode==0)try{e.keyCode=-1;break a}catch(r){k=j}if(k||e.returnValue==i)e.returnValue=j}}k=new Yc;k.ka(e,this);e=j;try{if(m){for(var o=[],B=k.currentTarget;B;B=B.parentNode)o.push(B);h=f[j];h.g=h.b;for(var A=o.length-1;!k.I&&A>=0&&h.g;A--)k.currentTarget=o[A],e&=gd(h,o[A],d,j,k);if(n){h=
f[q];h.g=h.b;for(A=0;!k.I&&A<o.length&&h.g;A++)k.currentTarget=o[A],e&=gd(h,o[A],d,q,k)}}else e=hd(c,k)}finally{if(o)o.length=0;k.F()}return e}d=new Yc(b,this);try{e=hd(c,d)}finally{d.F()}return e};function id(){}(function(a){a.Tb=function(){if(!a.Wb)a.Wb=new a}})(id);id.prototype.mb=0;id.Tb();function jd(){}F(jd,mc);t=jd.prototype;t.Wa=j;t.La=l;t.addEventListener=function(a,b,c,d){$b(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){cd(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=a.type||a,c=Y;if(b in c){if(z(a))a=new X(a,this);else if(a instanceof X)a.target=a.target||this;else{var d=a,a=new X(b,this);gb(a,d)}var d=1,f,c=c[b],b=j in c,e;if(b){f=[];for(e=this;e;e=e.La)f.push(e);e=c[j];e.g=e.b;for(var h=f.length-1;!a.I&&h>=0&&e.g;h--)a.currentTarget=f[h],d&=gd(e,f[h],a.type,j,a)&&a.qa!=q}if(q in c)if(e=c[q],e.g=e.b,b)for(h=0;!a.I&&h<f.length&&e.g;h++)a.currentTarget=f[h],d&=gd(e,f[h],a.type,q,a)&&a.qa!=q;else for(f=this;!a.I&&f&&e.g;f=f.La)a.currentTarget=
f,d&=gd(e,f,a.type,q,a)&&a.qa!=q;a=Boolean(d)}else a=j;return a};t.j=function(){jd.X.j.call(this);fd(this);this.La=l};function kd(){return j};function gc(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function ld(){this.pa=i}function ec(a){var b=[];md(new ld,a,b);return b.join("")}
function md(a,b,c){switch(typeof b){case "string":nd(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(w(b)){var d=b.length;c.push("[");for(var f="",e=0;e<d;e++)c.push(f),f=b[e],md(a,a.pa?a.pa.call(b,String(e),f):f,c),f=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),nd(e,c),c.push(":"),
md(a,a.pa?a.pa.call(b,e,f):f,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var od={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},pd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function nd(a,b){b.push('"',a.replace(pd,function(a){if(a in od)return od[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return od[a]=f+b.toString(16)}),'"')};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var qd=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!z(a))return[a];if(z(c)&&(c=z(c)?document.getElementById(c):c,!c))return[];var c=c||document,e=c.ownerDocument||c.documentElement;la=c.contentType&&c.contentType=="application/xml"||La&&(c.doctype||e.toString()=="[object XMLDocument]")||!!e&&(H?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.na?e:b(e)}function b(a){if(a&&a.na)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(a.length<2)return b;
V++;if(H&&la){var c=V+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(H&&a.Mb)try{for(d=1;e=a[d];d++)D(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=V);for(d=1;e=a[d];d++)a[d]._zipIdx!=V&&b.push(e),e._zipIdx=V}return b}function c(a,b){if(!b)return 1;var c=Od(a);return!b[c]?b[c]=1:0}function d(a,b){if(xc){var c=yc[a];if(c&&!b)return c}if(c=zc[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");a.indexOf("#")>=
0&&e&&(b=j);if(xc&&!b&&">~+".indexOf(c)==-1&&(!H||a.indexOf(":")==-1)&&!(Ac&&a.indexOf(".")>=0)&&a.indexOf(":contains")==-1&&a.indexOf("|=")==-1){var h=">~+".indexOf(a.charAt(a.length-1))>=0?a+" *":a;return yc[a]=function(b){try{9==b.nodeType||e||g("");var c=b.querySelectorAll(h);H?c.Mb=j:c.na=j;return c}catch(f){return d(a,j)(b)}}}else{var k=a.split(/\s*,\s*/);return zc[a]=k.length<2?f(a):function(a){for(var b=0,c=[],d;d=k[b++];)c=c.concat(f(d)(a));return c}}}function f(a){var b=Bc(ra(a));if(b.length==
1){var c=e(b[0]);return function(a){if(a=c(a,[]))a.na=j;return a}}return function(a){for(var a=ma(a),c,d,f=b.length,wc,h,xb=0;xb<f;xb++){h=[];c=b[xb];d=a.length-1;if(d>0)wc={},h.na=j;d=e(c);for(var k=0;c=a[k];k++)d(c,h,wc);if(!h.length)break;a=h}return h}}function e(a){var b=Cc[a.J];if(b)return b;var c=a.hb,c=c?c.oa:"",d=k(a,{G:1}),e="*"==a.f,f=document.getElementsByClassName;if(c){f={G:1};if(e)f.f=1;d=k(a,f);"+"==c?b=n(d):"~"==c?b=m(d):">"==c&&(b=h(d))}else if(a.id)d=!a.jb&&e?kd:k(a,{G:1,id:1}),
b=function(b,c){var e=Pc(b).fb(a.id);if(e&&d(e))if(9==b.nodeType)return ma(e,c);else{for(var f=e.parentNode;f;){if(f==b)break;f=f.parentNode}if(f)return ma(e,c)}};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.n.length&&!Ac)var d=k(a,{G:1,n:1,id:1}),o=a.n.join(" "),b=function(a,b){for(var c=ma(0,b),e,f=0,h=a.getElementsByClassName(o);e=h[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.jb?b=function(b,c){for(var d=ma(0,c),e,f=0,h=b.getElementsByTagName(a.Ea());e=h[f++];)d.push(e);return d}:
(d=k(a,{G:1,f:1,id:1}),b=function(b,c){for(var e=ma(0,c),f,h=0,Nd=b.getElementsByTagName(a.Ea());f=Nd[h++];)d(f,b)&&e.push(f);return e});return Cc[a.J]=b}function h(a){a=a||kd;return function(b,d,e){for(var f=0,h=b[Dc];b=h[f++];)Ea(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function m(a){return function(b,d,e){for(b=b[Fa];b;){if(Ea(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[Fa]}return d}}function n(a){return function(b,d,e){for(;b=b[Fa];)if(!Ra||D(b)){(!e||c(b,e))&&a(b)&&d.push(b);break}return d}}
function k(a,b){if(!a)return kd;var b=b||{},c=l;b.G||(c=na(c,D));b.f||a.f!="*"&&(c=na(c,function(b){return b&&b.tagName==a.Ea()}));b.n||O(a.n,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=na(c,function(a){return d.test(a.className)});c.fa=b});b.C||O(a.C,function(a){var b=a.name;yb[b]&&(c=na(c,yb[b](b,a.value)))});b.da||O(a.da,function(a){var b,d=a.va;a.type&&Ec[a.type]?b=Ec[a.type](d,a.Ja):d.length&&(b=Pd(d));b&&(c=na(c,b))});b.id||a.id&&(c=na(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=kd);return c}function r(a){return B(a)%2}function o(a){return!(B(a)%2)}function B(a){var b=a.parentNode,c=0,d=b[Dc],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&e>=0&&f>=0)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Fa])if(Ea(b))b._i=++c,a===b&&(e=c);return e}function A(a){for(;a=a[Fa];)if(Ea(a))return q;return j}function s(a){for(;a=a[Qd];)if(Ea(a))return q;return j}function p(a,b){return!a?"":b=="class"?a.className||"":b=="for"?a.htmlFor||"":b=="style"?a.style.cssText||
"":(la?a.getAttribute(b):a.getAttribute(b,2))||""}function D(a){return 1==a.nodeType}function na(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Bc(a){function b(){if(n>=0)u.id=c(n,x).replace(/\\/g,""),n=-1;if(o>=0){var a=o==x?l:c(o,x);">~+".indexOf(a)<0?u.f=a:u.oa=a;o=-1}m>=0&&(u.n.push(c(m+1,x).replace(/\\/g,"")),m=-1)}function c(b,d){return ra(a.slice(b,d))}a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var d=[],e=-1,f=-1,h=-1,k=-1,m=-1,n=-1,
o=-1,r="",p="",A,x=0,B=a.length,u=l,s=l;r=p,p=a.charAt(x),x<B;x++)if(r!="\\")if(u||(A=x,u={J:l,C:[],da:[],n:[],f:l,oa:l,id:l,Ea:function(){return la?this.bc:this.f}},o=x),e>=0)if(p=="]"){s.va?s.Ja=c(h||e+1,x):s.va=c(e+1,x);if((e=s.Ja)&&(e.charAt(0)=='"'||e.charAt(0)=="'"))s.Ja=e.slice(1,-1);u.da.push(s);s=l;e=h=-1}else{if(p=="=")h="|~^$*".indexOf(r)>=0?r:"",s.type=h+p,s.va=c(e+1,x-h.length),h=x+1}else if(f>=0){if(p==")"){if(k>=0)s.value=c(f+1,x);k=f=-1}}else if(p=="#")b(),n=x+1;else if(p==".")b(),
m=x;else if(p==":")b(),k=x;else if(p=="[")b(),e=x,s={};else if(p=="(")k>=0&&(s={name:c(k+1,x),value:l},u.C.push(s)),f=x;else if(p==" "&&r!=p){b();k>=0&&u.C.push({name:c(k+1,x)});u.jb=u.C.length||u.da.length||u.n.length;u.Mc=u.J=c(A,x);u.bc=u.f=u.oa?l:u.f||"*";if(u.f)u.f=u.f.toUpperCase();if(d.length&&d[d.length-1].oa)u.hb=d.pop(),u.J=u.hb.J+" "+u.J;d.push(u);u=l}return d}function ma(a,b){var c=b||[];a&&c.push(a);return c}var Ac=J&&document.compatMode=="BackCompat",Dc=document.firstChild.children?
"children":"childNodes",la=q,Ec={"*=":function(a,b){return function(c){return p(c,a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return p(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+p(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+p(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){b=" "+b;return function(c){c=" "+p(c,a);return c==b||c.indexOf(b+"-")==0}},"=":function(a,b){return function(c){return p(c,a)==
b}}},Ra=typeof document.firstChild.nextElementSibling=="undefined",Fa=!Ra?"nextElementSibling":"nextSibling",Qd=!Ra?"previousElementSibling":"previousSibling",Ea=Ra?D:kd,yb={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return s},"last-child":function(){return A},"only-child":function(){return function(a){return!s(a)?q:!A(a)?q:j}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;
if(c===1||c==3)return q}return j}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=Bc(b)[0],d={G:1};if(c.f!="*")d.f=1;if(!c.n.length)d.n=1;var e=k(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if(b=="odd")return r;else if(b=="even")return o;if(b.indexOf("n")!=-1){var c=b.split("n",2),d=c[0]?c[0]=="-"?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,h=-1;d>0?e<0?e=e%d&&d+
e%d:e>0&&(e>=d&&(f=e-e%d),e%=d):d<0&&(d*=-1,e>0&&(h=e,e%=d));if(d>0)return function(a){a=B(a);return a>=f&&(h<0||a<=h)&&a%d==e};else b=e}var k=parseInt(b,10);return function(a){return B(a)==k}}},Pd=H?function(a){var b=a.toLowerCase();b=="class"&&(a="className");return function(c){return la?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},Cc={},zc={},yc={},xc=!!document.querySelectorAll&&(!J||K("526")),V=0,Od=H?function(a){return la?a.getAttribute("_uid")||
a.setAttribute("_uid",++V)||V:a.uniqueID}:function(a){return a._uid||(a._uid=++V)};a.C=yb;return a}();E("goog.dom.query",qd);E("goog.dom.query.pseudos",qd.C);function rd(){P.call(this)}F(rd,P);var sd=document.createElement("div");function Xb(a){sd.innerHTML=a;return sd.removeChild(sd.firstChild)};var td={mc:["BC","AD"],lc:["Before Christ","Anno Domini"],oc:"J,F,M,A,M,J,J,A,S,O,N,D".split(","),vc:"J,F,M,A,M,J,J,A,S,O,N,D".split(","),nc:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),uc:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),rc:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),xc:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),Bc:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),
zc:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),tc:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),yc:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),pc:"S,M,T,W,T,F,S".split(","),wc:"S,M,T,W,T,F,S".split(","),sc:["Q1","Q2","Q3","Q4"],qc:["1st quarter","2nd quarter","3rd quarter","4th quarter"],jc:["AM","PM"],kc:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],Ac:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],yb:6,Cc:[5,6],zb:5};function ud(a,b,c){ea(a)?(this.a=new Date(a,b||0,c||1),vd(this,c||1)):ga(a)?(this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate()),vd(this,a.getDate())):(this.a=new Date,this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0))}t=ud.prototype;t.ia=td.yb;t.ja=td.zb;t.p=function(){var a=new ud(this.a);a.ia=this.ia;a.ja=this.ja;return a};t.getFullYear=function(){return this.a.getFullYear()};t.getYear=function(){return this.getFullYear()};t.getMonth=function(){return this.a.getMonth()};
t.getDate=function(){return this.a.getDate()};t.getTime=function(){return this.a.getTime()};t.getUTCHours=function(){return this.a.getUTCHours()};t.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};function wd(a){a=a.getTimezoneOffset();if(a==0)a="Z";else var b=Math.abs(a)/60,c=Math.floor(b),b=(b-c)*60,a=(a>0?"-":"+")+G(c)+":"+G(b);return a}t.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};t.setFullYear=function(a){this.a.setFullYear(a)};t.setMonth=function(a){this.a.setMonth(a)};
t.setDate=function(a){this.a.setDate(a)};
t.add=function(a){if(a.ic||a.Zb){var b=this.getMonth()+a.Zb+a.ic*12,c=this.getYear()+Math.floor(b/12);b%=12;b<0&&(b+=12);var d;a:{switch(b){case 1:d=c%4==0&&(c%100!=0||c%400==0)?29:28;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.Nb&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+a.Nb*864E5),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),
this.setDate(a.getDate()),vd(this,a.getDate()))};t.$=function(a,b){return[this.getFullYear(),G(this.getMonth()+1),G(this.getDate())].join(a?"-":"")+(b?wd(this):"")};t.toString=function(){return this.$()};function vd(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}t.valueOf=function(){return this.a.valueOf()};function Ub(a,b,c,d,f,e,h){this.a=ea(a)?new Date(a,b||0,c||1,d||0,f||0,e||0,h||0):new Date(a?a.getTime():C())}F(Ub,ud);t=Ub.prototype;t.getHours=function(){return this.a.getHours()};
t.getMinutes=function(){return this.a.getMinutes()};t.getSeconds=function(){return this.a.getSeconds()};t.getMilliseconds=function(){return this.a.getMilliseconds()};t.getUTCHours=function(){return this.a.getUTCHours()};t.setHours=function(a){this.a.setHours(a)};t.setMinutes=function(a){this.a.setMinutes(a)};t.setSeconds=function(a){this.a.setSeconds(a)};t.setMilliseconds=function(a){this.a.setMilliseconds(a)};t.setUTCHours=function(a){this.a.setUTCHours(a)};
t.add=function(a){ud.prototype.add.call(this,a);a.Vb&&this.setHours(this.a.getHours()+a.Vb);a.Yb&&this.setMinutes(this.a.getMinutes()+a.Yb);a.ec&&this.setSeconds(this.a.getSeconds()+a.ec)};t.$=function(a,b){var c=ud.prototype.$.call(this,a);return a?c+" "+G(this.getHours())+":"+G(this.getMinutes())+":"+G(this.getSeconds())+(b?wd(this):""):c+"T"+G(this.getHours())+G(this.getMinutes())+G(this.getSeconds())+(b?wd(this):"")};t.toString=function(){return this.$()};
t.p=function(){var a=new Ub(this.a);a.ia=this.ia;a.ja=this.ja;return a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function xd(a,b){this.ea=[];this.Dc=a;this.Pb=b||l}t=xd.prototype;t.P=q;t.S=q;t.V=0;t.qb=q;t.Jb=q;t.Gb=0;t.Ua=function(a,b){yd(this,a,b);this.V--;this.V==0&&this.P&&zd(this)};function yd(a,b,c){a.P=j;a.Ma=c;a.S=!b;zd(a)}function Ad(a){if(a.P)a.qb||g(new Bd(a)),a.qb=q}function Cd(a,b,c,d){a.ea.push([b,c,d]);a.P&&zd(a)}function Dd(a){return ib(a.ea,function(a){return fa(a[1])})}
function zd(a){a.Na&&a.P&&Dd(a)&&(v.clearTimeout(a.Na),delete a.Na);a.A&&(a.A.Gb--,delete a.A);for(var b=a.Ma,c=q,d=q;a.ea.length&&a.V==0;){var f=a.ea.shift(),e=f[0],h=f[1],f=f[2];if(e=a.S?h:e)try{var m=e.call(f||a.Pb,b);if(m!==i)a.S=a.S&&(m==b||m instanceof Error),a.Ma=b=m;b instanceof xd&&(d=j,a.V++)}catch(n){b=n,a.S=j,Dd(a)||(c=j)}}a.Ma=b;if(d&&a.V)Cd(b,pa(a.Ua,a,j),pa(a.Ua,a,q)),b.Jb=j;if(c)a.Na=v.setTimeout(function(){g(new Ed(b))},0)}function Bd(a){L.call(this);this.Fc=a}F(Bd,L);
Bd.prototype.message="Already called";function Ed(a){L.call(this);this.Ec=a;this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}F(Ed,L);function Fd(a,b){var c=b||{},d=c.document||document,f=document.createElement("SCRIPT"),e={ob:f,Y:i},h=new xd(Gd,e),m=l,n=c.timeout!=l?c.timeout:5E3;if(n>0)m=window.setTimeout(function(){Hd(f,j);var b=new Id(Jd,"Timeout reached for loading script "+a);Ad(h);yd(h,q,b)},n),e.Y=m;f.onload=f.onreadystatechange=function(){if(!f.readyState||f.readyState=="loaded"||f.readyState=="complete")Hd(f,c.Kb||q,m),Ad(h),yd(h,j,l)};f.onerror=function(){Hd(f,j,m);var b=new Id(Kd,"Error while loading script "+a);Ad(h);
yd(h,q,b)};Rc(f,{type:"text/javascript",charset:"UTF-8",src:a});Ld(d).appendChild(f);return h}function Ld(a){var b=a.getElementsByTagName("HEAD");return!b||b.length==0?a.documentElement:b[0]}function Gd(){if(this&&this.ob){var a=this.ob;a&&a.tagName=="SCRIPT"&&Hd(a,j,this.Y)}}function Hd(a,b,c){c!=l&&v.clearTimeout(c);a.onload=ca;a.onerror=ca;a.onreadystatechange=ca;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var Kd=0,Jd=1;
function Id(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);L.call(this,c);this.code=a}F(Id,L);function fc(a,b){this.aa=new vb(a);this.Hb=b?b:"callback";this.Y=5E3}var Md=0;fc.prototype.send=function(a,b,c,d){a=a||l;d=d||"_"+(Md++).toString(36)+C().toString(36);v._callbacks_||(v._callbacks_={});var f=this.aa.p();if(a)for(var e in a)(!a.hasOwnProperty||a.hasOwnProperty(e))&&Mb(f,e,a[e]);b&&(v._callbacks_[d]=Rd(d,b),Mb(f,this.Hb,"_callbacks_."+d));b=Fd(f.toString(),{timeout:this.Y,Kb:j});Cd(b,l,Sd(d,a,c),i);return{Ic:d,Gc:b}};function Sd(a,b,c){return function(){Td(a,q);c&&c(b)}}
function Rd(a,b){return function(c){Td(a,j);b.apply(i,arguments)}}function Td(a,b){v._callbacks_[a]&&(b?delete v._callbacks_[a]:v._callbacks_[a]=ca)};H||I&&K("1.9.3");function Zb(a,b){this.la=a||1;this.Z=b||Ud;this.wa=pa(this.gc,this);this.Ia=C()}F(Zb,jd);Zb.prototype.enabled=q;var Ud=v.window;t=Zb.prototype;t.D=l;t.gc=function(){if(this.enabled){var a=C()-this.Ia;if(a>0&&a<this.la*0.8)this.D=this.Z.setTimeout(this.wa,this.la-a);else if(this.dispatchEvent(ac),this.enabled)this.D=this.Z.setTimeout(this.wa,this.la),this.Ia=C()}};t.start=function(){this.enabled=j;if(!this.D)this.D=this.Z.setTimeout(this.wa,this.la),this.Ia=C()};
t.stop=function(){this.enabled=q;if(this.D)this.Z.clearTimeout(this.D),this.D=l};t.j=function(){Zb.X.j.call(this);this.stop();delete this.Z};var ac="tick";function Vd(a){this.Hc=a||Pc();P.call(this)}F(Vd,P);t=Vd.prototype;t.Ob=l;t.Sb=l;t.Ib=l;t.set=function(a,b,c,d){P.prototype.set.call(this,a,b);if(c)this.Ob=a;if(d)this.Ib=a;return this};function $(a,b,c,d){return a.set(b.key,b.caption,c,d)}t.fb=aa("Sb");var Wd={key:"ok",caption:"Tamam"},Xd={key:"cancel",caption:"Vazge\u00e7"},Yd={key:"yes",caption:"Evet"},Zd={key:"no",caption:"Hay\u0131r"},$d={key:"save",caption:"Kaydet"},ae={key:"continue",caption:"Devam Et"};
typeof document!="undefined"&&($(new Vd,Wd,j,j),$($(new Vd,Wd,j),Xd,q,j),$($(new Vd,Yd,j),Zd,q,j),$($($(new Vd,Yd),Zd,j),Xd,q,j),$($($(new Vd,ae),$d),Xd,j,j));Hc("goog.net.XhrIo");window.onload=function(){new rd;new vb(window.location);E("HandsomeWidget",T);E("HandsomeWidget.prototype.AddEvent",T.prototype.xb);E("HandsomeWidget.prototype.RemoveEvent",T.prototype.Cb);E("HandsomeWidget.prototype.GetRowColumns",T.prototype.Bb);E("HandsomeWidget.prototype.GetResponseData",T.prototype.Ab);E("HandsomeWidget.prototype.StopListener",T.prototype.Eb);E("HandsomeWidget.prototype.StartListener",T.prototype.Db);console.info("HandsomeWidget 1.1.4");console.info("HandsomeWidget.prototype.AddEvent");
console.info("HandsomeWidget.prototype.RemoveEvent");console.info("HandsomeWidget.prototype.GetRowColumns");console.info("HandsomeWidget.prototype.GetResponseData");console.info("HandsomeWidget.prototype.StopListener");console.info("HandsomeWidget.prototype.StartListener")};})()
